### ISSUE TITLE
selection color is hard to see

### ISSUE THREAD

**Issue by luisrudge** [robb0wen/synthwave-vscode#1]
![image](https://user-images.githubusercontent.com/941075/56914362-4cead400-6a8a-11e9-92bc-9d383f4f0c63.png)

**Comment by dennislindsey** [comment]
You can try adding this to your `settings.json`:

```
    "workbench.colorCustomizations": {
        "[SynthWave '84]": {
            "editor.selectionBackground": "#463465"
        }
    },
```

The default color is #231a33, #463465 is twice as bright.

**Comment by luisrudge** [comment]
@dennislindsey Thanks! This is perfect for me. I'll send a PR to see if @robb0wen likes it 😬
