### ISSUE TITLE
Error with the theme

### ISSUE THREAD

**Issue by Jamalc0m** [robb0wen/synthwave-vscode#10]
Am getting this error when I installed the theme

![image](https://user-images.githubusercontent.com/8554119/56954026-7406db80-6b46-11e9-9d3d-68dd0f737e96.png)

**Comment by Chuckytuh** [comment]
> At this point, VS Code may pop up a message to say that it is corrupted, this is caused by the custom CSS & JS extension and not this theme. As their installation instructions say, you can click "Don't show again" to dismiss the popup.

from: https://marketplace.visualstudio.com/items?itemName=RobbOwen.synthwave-vscode

**Comment by Jamalc0m** [comment]
But the glow is not showing in the code, I have downloaded the css file.

**Comment by robb0wen** [comment]
Hi! Have you placed the json snippet into your editor's `settings.json` file?
You can do this by going to preferences > settings and then either clicking on the { } icon in the top right, or on any of the 'edit settings.json' links on that page.

**Comment by shashankKeshava** [comment]
@robb0wen I've placed the snippet in settings.json still I don't see the glow.

```
 "vscode_custom_css.imports": [
        "file:///Users/skeshava/Documents/synthwave84.css"
    ]```

**Comment by emmaadesile** [comment]
I also have the same issue. I've placed the snippet in `settings.json` and enabled custom CSS and JS, but the glow doesn't show.

**Comment by Jamalc0m** [comment]
@robb0wen I have already done it but the glow doesn't show.

**Comment by f4ww4z** [comment]
I've the same issue that @Jamalc0m is having.

**Comment by robb0wen** [comment]
Are any of you able to share the contents of your editor's settings.json file? I might be able to help debug if I can see the settings

**Comment by nicholasjon** [comment]
You bet: 

```{
    "workbench.startupEditor": "newUntitledFile",
    "window.zoomLevel": 0,
    "sublimeTextKeymap.promptV3Features": true,
    "editor.multiCursorModifier": "ctrlCmd",
    "editor.snippetSuggestions": "top",
    "editor.formatOnPaste": false,
    "editor.fontSize": 15,
    "vscode_custom_css.imports": ["file:///Users/nick/synthwave84/synthwave84.css"],
    "vscode_custom_css.policy": true,
    "workbench.colorTheme": "SynthWave '84"
}
```

**Comment by mkubrycz** [comment]
Hey guys, did you follow the **Getting Started** instructions for the [vscode-custom-css](https://github.com/be5invis/vscode-custom-css) extension?
Look at 3rd point, maybe you missed this part about permissions?

**Comment by nicholasjon** [comment]
Good check -- I did change the ownership of the Electron file though. 
```
➜  ~  ls -alh /Applications/Visual\ Studio\ Code.app/Contents/MacOS/Electron
-rwxr-xr-x  1 nick  staff    41K Apr 11 01:35 /Applications/Visual Studio Code.app/Contents/MacOS/Electron```

**Comment by nicholasjon** [comment]
Okay, sorry. Maybe that was it, when I was verifying that I performed the `chown` I did rerun it. When I popped back to VSCode I happened to rerun the "Reload Custom CSS and JS" command and voila it's there. I'm all good at this point, thanks folks. (Now to show off to my coworkers.)

**Comment by shashankKeshava** [comment]
> Okay, sorry. Maybe that was it, when I was verifying that I performed the `chown` I did rerun it. When I popped back to VSCode I happened to rerun the "Reload Custom CSS and JS" command and voila it's there. I'm all good at this point, thanks folks. (Now to show off to my coworkers.)

Reload CSS and JS fixed my issue

**Comment by pulberg** [comment]
ugh, i've chown/chgrp the hell out of the vscode/Electron and still get message about needing to "run vscode with admin privs...." any ideas?

**Comment by fornazierr** [comment]
This is my settings.json, and the theme works fine, on Windows 10, VSCode version 1.3.1.

`{
"workbench.startupEditor": "newUntitledFile",
"vscode_custom_css.imports": ["file:///C:/Users/lordd/.vscode/extensions/robbowen.synthwave-vscode-0.0.4/synthwave84.css"],
"workbench.colorTheme": "SynthWave '84",
"vscode_custom_css.imports": ["file:///C:/Users/lordd/.vscode/extensions/robbowen.synthwave-vscode-0.0.4/synthwave84.css"],
"vscode_custom_css.policy": true
}`
Result [here](http://prntscr.com/niunnh)

**Comment by jfedgar** [comment]
I had a similar problem on macos. I followed all instructions, and triple checked all permissions. When I hit "Reload custom CSS and JS" nothing happened ... no messages, no prompt to restart, nothing.

Then I hit 'check for updates' in vscode and got the error "Cannot update while running on a read-only volume. The application is on a read-only volume. Please move the application and try again. If you're on macOS Sierra or later, you'll need to move the application out of the Downloads directory. See this link for more information.". 

It turns out I still had vscode installed on my desktop (doh!). 

I moved it to the applications folder, as instructed, and still couldn't update (nor did the glow work).

So followed the instructions in the last comment here: https://github.com/Microsoft/vscode/issues/7426#issuecomment-425093469 (Workaround 2) then restarted and voila! Updates downloaded and hitting "Reload custom CSS and JS" warned me about potential corruption messages and prompted me to restart. 

After restarting I had a nice shiny glow!

**Comment by robb0wen** [comment]
I'm going to close this as it seems like the majority of these issues were permissions based from the extension dependency. Glad you got it working in the end.

**Comment by Jamalc0m** [comment]
Folks, i have tried everything from permissions to the restarting and all the steps mentioned .. but still didn't work!
