### ISSUE TITLE
Support Fragments

### ISSUE THREAD

**Issue by AAverin** [robb0wen/synthwave-vscode#104]
React Fragments `<><div></div></>` syntax breaks highlighting. I already checked VScode tickets and looks like they fixed fragments support, so it's now up to the plugins to support it too

Thanks

**Comment by hadriengerard** [comment]
The theme behaves well with the fragments.

<img width="1009" alt="Capture d’écran 2019-09-09 à 14 16 50" src="https://user-images.githubusercontent.com/7127805/64530333-29277c80-d30d-11e9-88fb-6f901295a806.png">

Are you sure it does not come from another plugin ?

**Comment by AAverin** [comment]
Hmm, this is the only styling plugin I use.
I'll keep digging then, thanks
