### ISSUE TITLE
Installed everything. Theme doesn't glow

### ISSUE THREAD

**Issue by DanyaKreyg** [robb0wen/synthwave-vscode#105]
Hello everyone and thank for your patience.
I have Installed everything and followed the instructions.  I had some issues with installing but I  solved them. 
So my  problem is that the theme doesn't glow. JS extension work and respond to commands such as enable/reload/disable. The base SynthWave '84 works too.
As you can see I am in superuser mode (Administrator in Windows)
![bild](https://user-images.githubusercontent.com/46575772/64647964-4a29c380-d41a-11e9-9bde-ebed380048ef.png)

![bild](https://user-images.githubusercontent.com/46575772/64648414-22872b00-d41b-11e9-8327-2c6fa8246ca0.png)
![bild](https://user-images.githubusercontent.com/46575772/64648078-7e04e900-d41a-11e9-9a35-744f8037bc0d.png)

I have tried to reinstall everything several times, but it didn't work. 
Any suggestions?

**Comment by stevealexandre** [comment]
Hello,

Your path is not ok.
Follow the guide "Important: Make sure you include the file protocol in the path i.e. file://"

**Comment by DanyaKreyg** [comment]
> Make sure you includ

OMG. thank u a lot. How could i miss this small detail. <3
