### ISSUE TITLE
Enable Custom CSS and JS not working

### ISSUE THREAD

**Issue by jameka23** [robb0wen/synthwave-vscode#107]
After doing ALL the steps to enable to glow effect, I Cmd + Shift + P to open the command palette and run the "Enable Custom CSS and JS", VSCode doesn't prompt me to start up like it does when I ran the "Restart Custom CSS and JS" command, so therefore, I am not able to get the get the glow effect I want. Thanks

**Comment by stevealexandre** [comment]
Hi dude,

I will try to help you.
Which OS do you have ?

**Comment by jameka23** [comment]
@stevealexandre macOS Mojave

**Comment by stevealexandre** [comment]
Okay, can you share your json configuration please.
By the way, the popup about custom js has show up or not ?

**Comment by jameka23** [comment]
{
    "workbench.startupEditor": "newUntitledFile",
    "editor.wordWrap": "on",
    "window.zoomLevel": 0,
    "[json]": {
        "editor.defaultFormatter": "HookyQR.beautify"
    },
    "[javascript]": {
        "editor.defaultFormatter": "vscode.typescript-language-features"
    },
    "workbench.colorTheme": "SynthWave '84",
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "[html]": {
        "editor.defaultFormatter": "vscode.html-language-features"
    },
    "vscode_custom_cs.imports": [
         "file:///Users/jamekaechols/synthwave84.css"
        ],
    "vscode_custom_cs.policy": true
}
 and yes the pop up shows...I’ll get a screenshot
@stevealexandre

**Comment by jameka23** [comment]
<img width="489" alt="Screen Shot 2019-09-26 at 9 01 05 AM" src="https://user-images.githubusercontent.com/14102749/65695174-a4db3600-e03c-11e9-8236-5cbf5dbbb337.png">

**Comment by stevealexandre** [comment]
okay to be sure, when you hit "restart wivusl studio code", glow still not activated ?
Can you verify that the css file is present in the path you have specify "/Users/jamekaechols/synthwave84.css"?

**Comment by jameka23** [comment]
Correct, it does not activate the glow when I restart visual studio code

<img width="580" alt="Screen Shot 2019-09-26 at 9 08 58 AM" src="https://user-images.githubusercontent.com/14102749/65695526-537f7680-e03d-11e9-9d2b-a3a8be722776.png">

**Comment by stevealexandre** [comment]
Ok so it should be a permission trouble on your vscode certainly.
vscode should be owned by your user.
Check this thread : https://github.com/microsoft/vscode/issues/7426#issuecomment-425093469

**Comment by jameka23** [comment]
@stevealexandre are you talking about the 
`sudo chown $USER ~/Library/Caches/com.microsoft.VSCode.ShipIt/*`
`xattr -dr com.apple.quarantine /Applications/Visual\ Studio\ Code.app`

**Comment by stevealexandre** [comment]
No sorry wrong link, from the readme of the js custom extension :

> Mac and Linux users
The extension would NOT if Code cannot modify itself. The cases include:

Code files being read-only, like on a read-only file system or,
Code is not started with the permissions to modify itself.
You need to claim ownership on Code's installation directory, by running this command:

sudo chown -R $(whoami) <Path to Code>
The placeholder <Path to Code> means the path to VSCode installation. It is typically:

/Applications/Visual Studio Code.app/Contents/MacOS/Electron, on MacOS;
/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron, on MacOS when using Insiders branch;
/usr/share/code, on most Linux;
/opt/visual-studio-code/ on Arch Linux.
Mac and Linux package managers may have customized installation path. Please double check your path is correct.

**Comment by jameka23** [comment]
<img width="579" alt="Screen Shot 2019-09-26 at 10 48 25 AM" src="https://user-images.githubusercontent.com/14102749/65703920-35b90e00-e04b-11e9-9afa-a0f779927de0.png">

So I did everything that was given to me lol including the README, which was straightforward. Dumb question..does vscode update automatically ?

**Comment by stevealexandre** [comment]
just let the cmd $(whoami). It's a special function which will convert it to your username. Don't need to put $username.
yes if you have activate the auto update and you will have to reconfigure glow everytime as specified in the doc.

**Comment by jameka23** [comment]
im in the `/users/jamekaechols` pwd

**Comment by stevealexandre** [comment]
The path you enter after the chown of course ....
Verify that the application is really installed there etc...

**Comment by jameka23** [comment]
@stevealexandre another dumb question ..what's the command to see where an application is downloaded?

**Comment by stevealexandre** [comment]
Easy : try simply to browse the path given `cd /Applications/Visual Studio Code.app/Contents` then "ls" (you can also use a directory viewer I guess)

Harder(not sure if working on mac) : `which code` which will given where the bin is reference and then `ll <path_given_by_which>` to see the symbolic link to the real path.

**Comment by robb0wen** [comment]
Not sure if you are still having issues but, as Synthwave has been updated to no longer need this plugin, I'd advise updating to the latest version and following the updated instructions.
