### ISSUE TITLE
VSCode 1.40 "Activity Bar Indicator"

### ISSUE THREAD

**Issue by willstocks** [robb0wen/synthwave-vscode#113]
VSCode 1.40 added an "Activity Bar Indicator" to the active items in the Activity Bar, which adds a little white overlay border on the left-hand-side:

![image](https://user-images.githubusercontent.com/43744514/68680256-45d47080-0559-11ea-8f9b-38b4afdd5e6f.png)

I could `display: none;` it, but obviously that wouldn't apply to all and not sure if it's the "cleanest" approach

**Comment by robb0wen** [comment]
This will be removed in the upcoming v0.1.0

**Comment by robb0wen** [comment]
Fixed in v0.1.0
