### ISSUE TITLE
No string highlight in Dart

### ISSUE THREAD

**Issue by Kuhjuice** [robb0wen/synthwave-vscode#115]
There is **no syntax highlight** of **strings** when you code in **dart**.
Please tell me how to fix this :) 

Thanks

<img width="517" alt="Screenshot 2019-11-27 at 15 03 43" src="https://user-images.githubusercontent.com/34770756/69729786-d6e14500-111e-11ea-95fb-2645cf038233.png">

**Comment by SimonGhost** [comment]
Same problem when the vscode insider updated.

**Comment by robb0wen** [comment]
I'm closing off legacy issues, but I've improved Dart highlighting in v0.1.8 😀
