### ISSUE TITLE
I'm getting cannot read id of undefined error

### ISSUE THREAD

**Issue by fzs1994** [robb0wen/synthwave-vscode#116]
Just installed the theme and this shows:
![image](https://user-images.githubusercontent.com/10684213/69850189-b80cbb00-12a4-11ea-8d6e-3bfa13d50d1d.png)

**Comment by robb0wen** [comment]
Does this still happen in v0.1.0?

**Comment by fzs1994** [comment]
No. It is resolved. Thanks!
