### ISSUE TITLE
color changed VSCode 1.41.0

### ISSUE THREAD

**Issue by IM1T** [robb0wen/synthwave-vscode#118]

**Comment by ZXMLoveCXF** [comment]
me too

**Comment by drewtato** [comment]
Yup, just updated to 1.41.0 on windows and it's changed. It's still working as some elements are glowing, but it's not the same ones.

**Comment by barryblando** [comment]
looks like VSCode change some element names. 'Will wait for a fix.

**Comment by vinayakkulkarni** [comment]
yep can confirm, fudged up in newer update of VS Code

**Comment by JohnArcher** [comment]
Same here with 1.41.0, running on Windows. Looks quite ugly now. :-(

![image](https://user-images.githubusercontent.com/990724/70783317-e69c9280-1d88-11ea-8569-86599506a35d.png)

**Comment by wanxe** [comment]
Looks like VSCode has changed some .css classes?

**Comment by XavierBrinonECS** [comment]
@JohnArcher hey man, time to do some optional chaining :)

**Comment by IxquitilisSaid** [comment]
Same here... I had to downgrade VSCode because my OCD wouldn't let me work with the "buggy" colours.

**Comment by vinayakkulkarni** [comment]
I switched to [nightOwl](https://marketplace.visualstudio.com/items?itemName=sdras.night-owl) theme for a while till SynthWave is fixed.

**Comment by JohnArcher** [comment]
@XavierBrinonECS This is code from jQuery 1.8.3, not my code.

**Comment by robb0wen** [comment]
Thanks for letting me know. I'll try to get a fix for this as soon as I can.

**Comment by bobmagicii** [comment]
huh. i wasn't sure what was to blame TBH. for example my variables used to look like this

![image](https://user-images.githubusercontent.com/881944/70827381-bb2c9e80-1dae-11ea-9f19-350c3987ee49.png)

but now they look like what other people have shown above

![image](https://user-images.githubusercontent.com/881944/70827411-cc75ab00-1dae-11ea-815c-d6f931704b1e.png)

which according to the inspector is mtk6

![image](https://user-images.githubusercontent.com/881944/70827434-df887b00-1dae-11ea-89d1-21a645c629d4.png)

and i was like "well that looks like what the css is saying"

and then reading this thread im like wow they completely changed the meaning of what mtk6 means then omg rip robb.

**Comment by bobmagicii** [comment]
my personal edit. its not 1:1 faithful to your original i had tweaked a few colours and glows but might be good enough to get some people through their day. https://gist.github.com/bobmagicii/52e759a5ba959f97d7fc461dd8d6ef36

![image](https://user-images.githubusercontent.com/881944/70829469-75260980-1db3-11ea-947b-d7f372021a0b.png)

**Comment by robb0wen** [comment]
Haha it was inevitable to be honest, given that the glow was always a hack. Not sure how to make this backwards compatible, but I'll give it a crack

**Comment by bobmagicii** [comment]
i believe the vscode package json thing allows you to specify ranges, so your next release you should be able to target only the versions of code that changed things. not sure of the syntax offhand, but i've seen other extensions not even show in the store for versions out of range.

**Comment by mercteil** [comment]
I think colors did not change after 1.41 at least before activating "the glow"
After reloading CSS-in-JS

<img width="561" alt="Screenshot 2019-12-15 at 19 10 49" src="https://user-images.githubusercontent.com/36293774/70866158-de9e4780-1f6e-11ea-8357-142a859f6ac2.png">


<img width="568" alt="Screenshot 2019-12-15 at 19 10 06" src="https://user-images.githubusercontent.com/36293774/70866151-c6c6c380-1f6e-11ea-808a-d6259a0d952c.png">

**Comment by bobmagicii** [comment]
yeah, its the css's fault cuz its a crazy trick we're doing.

**Comment by vaaski** [comment]
i modified the original synthwave84.css to work with the class name changes, but unlike @bobmagicii's solution it's derived from the original without tweaks.

[Gist link](https://gist.github.com/vaaski/f4450c3aabf1ebcbfc9cebba3a37966f)

**Comment by hmmhmmhm** [comment]
@vaaski  savior!

**Comment by mercteil** [comment]
works, thanks

**Comment by bradtaniguchi** [comment]
Really got to change the title of this issue, since its not a macOS only issue. 

vaaski fix works tho, so it might not matter for long :smile:

**Comment by robb0wen** [comment]
Nice work @vaaski!! 

I've just pushed a [feature branch containing updates for a potential v0.1.0 release](https://github.com/robb0wen/synthwave-vscode/tree/feature/neon-dreams). This tentative release , dubbed __Neon Dreams__, removes the dependency for the CSS and JS plugin. Instead of the CSS file, it injects JS into the VS code workbench that programatically assigns the neon theme colours based on VS code's generated CSS. This will hopefully improve compatibility, and prevent the colours getting broken again if MS reassign any internal CSS.

I've also added a setting value to control the brightness of the neon glow (see the branch readme) :)

If anyone would be kind enough to help me test this, It'd be rad if you could download the branch and do a manual install (copy it into your vscode extensions folder, then click 'reload' from the extension menu in VS code).

You can enable the glow from the command palette with "Enable Neon Dreams"

**Comment by robb0wen** [comment]
Nice work @vaaski !!
For the time being, using @vaaski's CSS is the best option for fixing this.

I've just created an issue (#121) detailing my longer term fix for this issue, that will hopefully also improve compatibility going forwards

**Comment by EMXavier** [comment]
> Same here with 1.41.0, running on Windows. Looks quite ugly now. :-(
> 
> ![image](https://user-images.githubusercontent.com/990724/70783317-e69c9280-1d88-11ea-8569-86599506a35d.png)

I'm unsure if this is related, but have a look at the theme's configuration file:

`C:\Users\%USERNAME%\.vscode\extensions\robbowen.synthwave-vscode-0.0.7\themes\synthwave-color-theme.json`

After recent VSC update I noticed all of the green too—and that a lot of the _glow_ wasn't rendering. The theme's config file contained a hanging comma (around `line 406`). Maybe latest VSC build is more strict on JSON syntax for configuration files? Theme worked after correcting syntax and reloading  VSC.

**Comment by robb0wen** [comment]
That looks like the same issue. The Glow uses a separate CSS file that overwrites the theme json. The classnames in the latest VS code changed, so the Glow CSS no longer functions as it did. The Gist posted above should fix the issue for now

**Comment by ErSulba** [comment]
since the release of vscode 1.42 the solution provided by @vaaski [in this comment](https://github.com/robb0wen/synthwave-vscode/issues/118#issuecomment-565839694) is not longer reliable

**Comment by vaaski** [comment]
@ErSulba try the new feature branch from #121, maybe that fixes your issue. It's what I've been using.

**Comment by robb0wen** [comment]
This issue has been resolved in v0.1.0. Thanks again to @vaaski for the interim fix.
