### ISSUE TITLE
Merge actions aren't visible 

### ISSUE THREAD

**Issue by timdeschryver** [robb0wen/synthwave-vscode#12]
The text with merge actions isn't visible:

![image](https://user-images.githubusercontent.com/28659384/56958145-c0074f80-6b49-11e9-8edf-f7f4b4713a2e.png)

On hover:
![image](https://user-images.githubusercontent.com/28659384/56958151-c85f8a80-6b49-11e9-85a7-0e02beed2df8.png)

I tried to find the right properties to make a change but wasn't able to find them after a quick search.

With another theme it looks like:

![image](https://user-images.githubusercontent.com/28659384/56958209-f218b180-6b49-11e9-91f4-5dbf2957a66f.png)

**Comment by arsum04** [comment]
Same issue

**Comment by robb0wen** [comment]
I'll take a look. As I said in the readme I never originally intended on releasing this, so there are quite a few issues for things I hadn't encountered in the day or so I've been using the theme. I'll have a look through and get this sorted though 👍

**Comment by timdeschryver** [comment]
No rush @robb0wen , I'll also take a better look later this week. 
It's a great theme, thanks for creating it 🙏!
