### ISSUE TITLE
 Something happened to styles after the last VS code update

### ISSUE THREAD

**Issue by IPR-Kaspar** [robb0wen/synthwave-vscode#120]
![image](https://user-images.githubusercontent.com/54580256/70905439-887fe180-200c-11ea-90cb-f63395dcf4d7.png)
Something happened to styles after the last VS code update. It has wrong colors. no pink and purple

**Comment by epitonium** [comment]
Same for me here. Fixing it not helping.

**Comment by robb0wen** [comment]
Thanks for letting me know. There's already an open issue here https://github.com/robb0wen/synthwave-vscode/issues/118 - I'll update it there as soon as it's fixed.

I'm working on a quick patch to get it working again, as well as a longer term solution to prevent it happening again in future 👍
