### ISSUE TITLE
NEON DREAMS (v0.1.0) test version

### ISSUE THREAD

**Issue by robb0wen** [robb0wen/synthwave-vscode#121]
I've just pushed a [feature branch containing updates for a potential v0.1.0 release](https://github.com/robb0wen/synthwave-vscode/tree/feature/neon-dreams). This tentative release , dubbed __Neon Dreams__, removes the dependency for the CSS and JS plugin. 

Instead of the CSS files, it injects JS into the VS code workbench that programatically assigns the neon theme colours based on VS code's generated CSS. This will hopefully improve compatibility, and prevent the colours getting broken again if MS reassign any internal CSS.

I've also added a setting value to control the brightness of the neon glow (see the branch readme) 😀

It modifies the internals of VS code's electron app, so this is very much use-at-your-own-risk at the moment. If anyone would be kind enough to help me test this though, it'd be rad. You can download the branch and do a manual install (copy it into your vscode extensions folder, then click 'reload' from the extension menu in VS code).

You can enable the glow from the command palette with "Enable Neon Dreams".

**Comment by vaaski** [comment]
damn a brightness setting sounds really cool, will definitely try out later today!

**Comment by pulberg** [comment]
Testing on Mac OS 10.14.6, vscode v1.41.  I can't seem to get the brightness to change, but maybe it's too subtle and I just can't tell 🤷‍♂   I'll test again at night.

**Comment by robb0wen** [comment]
Ah looks like you'll need to disable, then re-enable neon to see any changes to the brightness setting. I'm going to add in a prompt to reload whenever it changes, which will hopefully make that clearer

**Comment by devshane** [comment]
I'm not sure if this qualifies as a bug with this particular release, but [Monkey Patch](https://github.com/iocave/monkey-patch) uses it's own workbench html file `workbench-monkey-patch.html`. Including the `neondreams.js` script in it seems to work fine.

(Thanks for this extension!)

**Comment by vaaski** [comment]
Not sure what I'm doing wrong, but I can not get the extension to load.
I cloned this repo into my `%USERPROFILE%\.vscode\extensions` folder and switched branches to [feature/neon-dreams](https://github.com/robb0wen/synthwave-vscode/tree/feature/neon-dreams). Nothing. Even ran `yarn` just to make sure. I also tried installing the extension from the extension store (which works) and manually pasting the contents of this branch over the store folder. It just doesn't show up. The Extension Host logs don't even mention the folder. It's also not in my disabled extensions.

Any idea what I could be doing wrong?

**Comment by robb0wen** [comment]
@vaaski VScode is a bit funny about folder names inside the extensions directory so what I did was copy the contents of the `feature/neon-dreams` into the existing installed folder i.e. `%USERPROFILE%\.vscode\extensions\robbowen.synthwave-vscode-0.0.7`.

Then, under installed extensions there was a 'reload required' button next to Synthwave '84. Clicking that updated to the manual v0.1.0

**Comment by JohnArcher** [comment]
I may had the same problem as @vaaski . So I took the steps @robb0wen mentioned in his previous post, but the "reload required" button did not appear. So I disabled the extension and enabled it again. _After_ that there was the reload button.

Then, I tried to enable via `Enable Neon Dreams`, but that had no effect. Additionally I had to **click the "Set Color Theme" button** on the extension site:

![image](https://user-images.githubusercontent.com/990724/70995940-022dd300-20d2-11ea-81a9-5745d4cf7038.png)

After that it finally worked (and looks beautiful as before).

One additional thing: The image links in the readme seem to be broken somehow, although the code of the .md looks good. I am on Windows.

![image](https://user-images.githubusercontent.com/990724/70996094-605ab600-20d2-11ea-8c25-95963303b955.png)

Either way thanks a lot for you work!

**Comment by robb0wen** [comment]
Glad to hear you got it working! The image links will be broken as it isn't published yet, but once I've eventually completed the PR and pushed to the marketplace it should be fine.

The glow not working until the theme is set is intentional - the code that gets injected checks to make sure that Synthwave is the current theme before applying the neon. The extra control means that it will hopefully circumvent a lot of the issues people were having with external CSS filepaths and permissions etc.

**Comment by JohnArcher** [comment]
@robb0wen Alright, I see. Makes sense. But then you should alter the documentation that you have to additionally click the "Set Color Theme" button. Or did I miss something?
Would be interesting to see whether this is/was also @vaaski 's problem.

**Comment by robb0wen** [comment]
Sure, please bear with me whilst it's still very WIP - the documentation and in-extension messaging are going to get more attention before the release is ready

**Comment by kokarn** [comment]
Worked for me without "Set Color Theme", not sure why. Looks great tho <3

**Comment by robb0wen** [comment]
If you're already using Synthwave as your active theme you won't need that step.

**Comment by JohnArcher** [comment]
@robb0wen Alright, no problem. I just wanted to make sure this point is not forgotten. :-)

**Comment by weswigham** [comment]
Hm, I've installed the feature branch, but when I "Enable Neon Dreams" in the menu, I get
![image](https://user-images.githubusercontent.com/2932786/71040244-07435000-20db-11ea-84a2-27c29f9adedb.png)

:(

**Comment by weswigham** [comment]
Looks like
```
EPERM: operation not permitted, open 'c:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-browser\workbench\neondreams.js'
```

- said file does not exist, upon inspection of my filesystem.

**Comment by weswigham** [comment]
Yah - the extension can't write to that folder by default. Needs admin permissions (launching vscode as administrator), or needs the folder permissions to be reassigned.

**Comment by vaaski** [comment]
I just tried doing it like @robb0wen described with @JohnArcher's disable-and-enable trick and it worked after a reload. 
But when I change the brightness setting it doesn't apply after a reload or restart, it only changes after disabling and re-enabling neon dreams.
vscode also doesn't recognize the setting.
![image](https://user-images.githubusercontent.com/17879327/71042568-60879f80-212c-11ea-98df-d69a3c99f893.png)

Other than that this is a fantastic theme, thanks for making it even better.

**Comment by robb0wen** [comment]
@vaaski Glad you got it working. I believe that the unrecognised setting is due to manually installing the plugin, but I'll double check to be sure. 

Changing the settings doesn't update on the fly as the enable command has to generate and inject new theme assets from a template. As I mentioned somewhere above, I'll update all of the messaging to make that requirement clearer.

@weswigham thanks for letting me know. I haven't had chance to test the new version on windows, so it's extremely useful to know about having to run as an administrator.

**Comment by vaaski** [comment]
Maybe you could add a re-enable command so you don't have to reload twice if that's possible🤔

**Comment by callit** [comment]
got it installed on my end. Installation was a bit finicky, but I expect that at this point.  It looks good though, back to the colors I expected.  I'll test with it a bit and let you know if I run into anything.  Thanks for keeping up with this - it is by far my favorite VSC theme :)

**Comment by glitchracer** [comment]
Hey Rob,

no luck here, did everything as you said, still the odd colors. 

Installed extensions shows Version 0.1.0, glow is there. 

I tried do deinstall, install an so on, nothing helps.

**Comment by glitchracer** [comment]
> @robb0wen no luck here, did everything as you said, still the odd colors.
> Installed extensions shows Version 0.1.0, glow is there. I tried do uninstall, install an so on, nothing helps.

Okay got it working by disabling custom CSS and JS.

**Comment by robb0wen** [comment]
Glad you got it working. I'll make sure to add something to the readme about disabling the custom CSS and js version - thanks!

Thanks again to everyone who's installed the test version and given it a whirl. Once I've worked through all of the feedback, I'll release v0.1.0 to the marketplace and hopefully all of the installation woes will be behind us 😀

**Comment by boltex** [comment]
(ubuntu 18.04) Made the glow work. But it was not super-easy... : I had to first : set myself as owner of vscode folder instead of root. Also I then had to remove it entirely, then re-install it, then re-enable it - otherwise it said the 'enable' command did not exits even though the theme was clearly visible (without glow). So yeah, it works but a newbie would not be able to set it up without either a much more detailed documentation / or / better 'error-checking' when enabling/installing. 

Anyways Thanks For This Great Theme Bro!!! it rocks just need to polish the install&activate procedures in order to give meaningfull messages when permissions are blocking the plugin or other issues that could be more precisely detected! :)

**Comment by Khaeops** [comment]
This is great! Got it working after some fiddling and the glow seems to work. I'm trying to edit the colours now but whenever I make a change I seem to lose the glow for that token's colour. I'm editing synthwave-color-theme.json, is that the right file I should be editing?

**Comment by robb0wen** [comment]
@Khaeops Glad you got it working. The neondreams.js file is generated each time the glow is enabled though, so be aware that your edits might get overwritten. This happens because the neon dreams update is tailored for the Synthwave colour theme rather than being an all-purpose glow extension. 

For custom tweaks and colours it's probably better to continue the Custom CSS and JS process and manually update the CSS.

**Comment by robb0wen** [comment]
@boltex, Thanks for letting me know. I'll update the documentation for Ubuntu based on your feedback. Permissions is a big part of installation as the extension has to modify the core workbench.html inside VS code.

**Comment by boltex** [comment]
@robb0wen Just re-read myself and thought i'd worded it wrong, when I said I had to reinstall after setting myself as owner, I meant just your extension not vscode entirely obviously.

**Comment by C0rporeus** [comment]
I managed to activate but you can't see the blur effect ... I did everything in the guide along with running in the version 0.1.0 npm install folder (according to the package.json I saw there) before I was not allowed to enable, After installation yes, I update and the tabs are seen with color variations ...
![neonblurno](https://user-images.githubusercontent.com/14317273/74280223-50cea680-4cea-11ea-92a1-9dbc1d1af210.png)

**Comment by C0rporeus** [comment]
I managed to activate but you can't see the blur effect ... I did everything in the guide along with running in the version 0.1.0 npm install folder (according to the package.json I saw there) before I was not allowed to enable, After installation yes, I update and the tabs are seen with color variations ...

10 minutes later ... I went to the standard css files I changed them and that solved it ... I would recommend that the documentation be extended and the correction of the css was done ... also the need to install nodeJs and run the package manager to update the theme package...

![neonblurno](https://user-images.githubusercontent.com/14317273/74280825-4bbe2700-4ceb-11ea-8068-15abb8cca4aa.png)

(already solved)

![neonblur](https://user-images.githubusercontent.com/14317273/74280835-4eb91780-4ceb-11ea-88d5-f5738f98c3af.png)

**Comment by matiasnoriega** [comment]
> I managed to activate but you can't see the blur effect ... I did everything in the guide along with running in the version 0.1.0 npm install folder (according to the package.json I saw there) before I was not allowed to enable, After installation yes, I update and the tabs are seen with color variations ...
> 
> 10 minutes later ... I went to the standard css files I changed them and that solved it ... I would recommend that the documentation be extended and the correction of the css was done ... also the need to install nodeJs and run the package manager to update the theme package...
> 
> ![neonblurno](https://user-images.githubusercontent.com/14317273/74280825-4bbe2700-4ceb-11ea-8068-15abb8cca4aa.png)
> 
> (already solved)
> 
> ![neonblur](https://user-images.githubusercontent.com/14317273/74280835-4eb91780-4ceb-11ea-88d5-f5738f98c3af.png)

How you manage to get that color pallette? I'm still getting the blue/greenish :(

**Comment by JohnArcher** [comment]
What do you mean by "blue/greenish"? Like in C0rporeus first screenshot? If yes, try this: Press `Ctrl+Shift+P` and then enter/execute `Synthwave '84: Enable Neon Dreams`

**Comment by matiasnoriega** [comment]
Sorry, I forgot to add a screenshot:

![greenish](https://i.imgur.com/oiQopuT.png)

I can't get it working right, and now that you mention it @JohnArcher I haven't the `Enable Neon Dreams` option on the `Ctrl+Shift+P` menu. I'm following all the steps and I can't make it work :/

**Comment by robb0wen** [comment]
@matiasnoriega is sounds like the issue you're having is with v0.0.7 rather than the feature branch  version.

Anyhow, I've just published v0.1.0 to the marketplace. Please uninstall the feature branch version and update from the marketplace.

Thanks all for your help in me getting this one done. It's really hard to support what is essentially a hack, and I really appreciate all of the feedback.

**Comment by JohnArcher** [comment]
@matiasnoriega I hope the new update helps in your situation!?

@robb0wen Great, thanks a lot for your work! Just one thing: In my `settings.json` there are no commands like `"synthwave84.brightness"` and `"synthwave84.disableGlow"` available!?

**Comment by matiasnoriega** [comment]
The new update fixed everything! Thank you @JohnArcher @robb0wen ! I was already missing this theme a lot <3

**Comment by ezequias** [comment]
I just woke up this morning and have this splendid news. It is working fine here. 

This extension could deal with json also, would be amazing have it in that kind of file also (as we have with .sql files).

![image](https://user-images.githubusercontent.com/539561/74533048-6a9d0300-4f0f-11ea-832c-8f1e65836e33.png)

**Comment by ezequias** [comment]
@vaaski for me it's working perfectly well.

Just uses Ctrl + Shift + P > Enable Neon Dreams and restart VS Code.

![image](https://user-images.githubusercontent.com/539561/74534081-bfda1400-4f11-11ea-9de4-2564eae98c48.png)

**Comment by ezequias** [comment]
Sunthwave makes my friday better.

![image](https://user-images.githubusercontent.com/539561/74534395-645c5600-4f12-11ea-966e-432eeee64879.png)

**Comment by ezequias** [comment]
![image](https://user-images.githubusercontent.com/539561/74542100-a214ab00-4f21-11ea-852a-2af0dbd2d459.png)
#OMG

**Comment by jeremytbrun** [comment]
@robb0wen After updating to v.0.1.0 it seems like the color scheme has changed a bit. I see others have mentioned similar issues but I'm unclear on whether this was supposed to have been fixed with 0.1.0...

I don't have a screenshot of what it previously was, but essentially it seems like anywhere that has the glow is much less vibrant in color. I kind of hope this is just a bug and not the new norm for color scheme. In the screenshot below the text color of the `Foreach-Object` calls are normally much more blue.

![image](https://user-images.githubusercontent.com/28311946/74559309-13f4f080-4f32-11ea-8299-f6b7b7cd11fb.png)

**Comment by ezequias** [comment]
> @robb0wen After updating to v.0.1.0 it seems like the color scheme has changed a bit. I see others have mentioned similar issues but I'm unclear on whether this was supposed to have been fixed with 0.1.0...
> 
> I don't have a screenshot of what it previously was, but essentially it seems like anywhere that has the glow is much less vibrant in color. I kind of hope this is just a bug and not the new norm for color scheme. In the screenshot below the text color of the `Foreach-Object` calls are normally much more blue.
> 
> ![image](https://user-images.githubusercontent.com/28311946/74559309-13f4f080-4f32-11ea-8299-f6b7b7cd11fb.png)
> 
> EDIT
> 
> What I was used to seeing before the update is a color scheme like the FIRST image in this post above by @C0rporeus only with the glow. It seems like the yellows, reds and blues that normally have a glow have become somewhat white and even the magenta/pink has become darker.
> 
> [#121 (comment)](https://github.com/robb0wen/synthwave-vscode/issues/121#issuecomment-584861252)
> 
> ![image](https://user-images.githubusercontent.com/28311946/74560536-c463f400-4f34-11ea-93ab-2132169de848.png)

Try to go to to Settings:
![image](https://user-images.githubusercontent.com/539561/74572147-6d264980-4f5d-11ea-9455-ba99bfe296c3.png)

Than the menu Workbench and look for "Editing in settingsjson" link

Than add in the the begining of the json file the following text:

"synthwave84.brightness": "0.20",

![image](https://user-images.githubusercontent.com/539561/74572327-b2e31200-4f5d-11ea-81be-1dd05d6223ac.png)

Save the file and press Ctrl + Shift + P and type 'Enable Neon Dreams' and restart VS Code.

VOILA!

**Comment by Kati3e** [comment]
So this doesn't seem to work if VS Code was installed via Snap. I was unable to change directory permissions for the Snap install. I had to install the official .deb and then I was able to change the permissions for `/usr/share/code/resources/app/out/vs/code/electron-browser/workbench` which allowed the extension's command to run. Thanks! It's so beautiful!

**Comment by andywampir** [comment]
I've enabled glow with admin rights, but i got [Installation appears to be corrupt [Unsupported]](https://code.visualstudio.com/docs/supporting/faq#_installation-appears-to-be-corrupt-unsupported) warning.
Is it normal?

**Comment by robb0wen** [comment]
@andywampir Yes that's normal, to enable the glow the extension needs to make a small modification to a core app file, which VS code detects as being 'corrupted'. As it says in the readme, you can dismiss that message by hitting the cog icon in the corner of the notification and choosing "don't show me this again" 👍

@JohnArcher Those settings need to be added manually if you want to make modifications to the default settings. By default, the brightness is set at 0.45, but you can increase that as needed.

Regarding the brightness of the glow, as mentioned above you can change that in your settings to increase or decrease as you need. I wanted to try and keep the default settings more accessible, but I might look at bumping up the default brightness in the next version.

**Comment by robb0wen** [comment]
I'll close this issue for now because it was related to the pre-release version of v0.1.0
Any new issues can be raised separately as it's easier to track them. 

Thanks again for the help on this release.

**Comment by deandex** [comment]
> So this doesn't seem to work if VS Code was installed via Snap. I was unable to change directory permissions for the Snap install. I had to install the official .deb and then I was able to change the permissions for `/usr/share/code/resources/app/out/vs/code/electron-browser/workbench` which allowed the extension's command to run. Thanks! It's so beautiful!

I have try to set chmod 777 for workbench folder but still unlucky to enable the neon dreams. Always get message "You must run VS code with admin priviliges in order to enable Neon Dreams."
Anyone can give advice to enable it on ubuntu ?

**Comment by boltex** [comment]
@deandex Check out my previous comment in this same thread : https://github.com/robb0wen/synthwave-vscode/issues/121#issuecomment-570301255

**Comment by deandex** [comment]
> @deandex Check out my previous comment in this same thread : [#121 (comment)](https://github.com/robb0wen/synthwave-vscode/issues/121#issuecomment-570301255)

Wow cool... thanks @boltex 
Now it's glow

**Comment by wellbishop** [comment]
For those who are having **troubles** on enabling the **glow effect** in **Ubuntu**, here is what I have done:

1. Close all VSCode windows;
2. From the terminal, run `sudo code --user-data-dir="~/.vscode-root"`;
3. Enable the Synth Theme Color;
4. CTRL+Shift+P -> Enable Neon Dreams. The editor will ask you to reload, do it;
5. Close the editor and open again without `sudo` and you'll see the glow effect.

**Comment by boltex** [comment]
@deandex Yeah, its normal because the rights to the folder are set to you and it detected it. also the plugin modified style sheets directly. But you can unfold choices for this message and choose : dont show again

**Comment by julekgwa** [comment]
If you are having root privilege issues on Linux, try running ```ls -al /usr/share/code```  to see the owner, if you are not the owner change it with ```sudo chown -R $(whoami) /usr/share/code``` and try enabling the glow, it should work now.

**Comment by Kenney-G** [comment]
None of these suggestions have worked for me. Works fine on Arch, but on Ubuntu which uses the vscode Snap version, making both the snap's directory and the config directory read-writable don't fix the issue.

**Comment by boltex** [comment]
@Kenney-G I didnt do any of those things to make it work on ubuntu with the snap version.
(making both the snap's directory and the config directory read-writable)
 I just made myself (my user, not the root user) owner of the vscode folder, removed completely the synthwave plugin (if you already installed it., not just disable it, locate the folder and delete it if you have to) Then (re)install it, then activate it.

**Comment by taciturasa** [comment]
I'm currently on elementaryOS Hera (18.04 under the hood), using VSCodium, and I haven't been able to get this working with any of the suggestions in this thread. At this point, I'm completely stumped. If it still used monkeypatch it'd likely still work - monkeypatch uses a sudo prompt instead of making you have to do a bunch of workarounds to get it to work.

It's a shame, because I really really wanted to use this effect. At the point, however, it simply does not seem possible.

**Comment by iHeadway** [comment]
> I just made myself (my user, not the root user) owner of the vscode folder, removed completely the synthwave plugin (if you already installed it., not just disable it, locate the folder and delete it if you have to) Then (re)install it, then activate it.
I can't find the folder (in extensions) and all other steps didn't work for me - still have the "command not found" error.

**Comment by Adamkaram** [comment]
> ![image](https://user-images.githubusercontent.com/539561/74542100-a214ab00-4f21-11ea-852a-2af0dbd2d459.png) #OMG

how i can add this lamp ?

**Comment by mycosavant** [comment]
> > ![image](https://user-images.githubusercontent.com/539561/74542100-a214ab00-4f21-11ea-852a-2af0dbd2d459.png) #OMG
> 
> how i can add this lamp ?

this is the custom css from editor_chrome.css:
`* update lightbulb to be neon */
.codicon-lightbulb-autofix:before,
.codicon-light-bulb:before, .codicon-lightbulb:before {
  content: '';
}

.codicon-lightbulb-autofix:before
.codicon-light-bulb:before, .codicon-lightbulb:before,
.lightbulb-glyph {
  background:  url("data:image/svg+xml,%3Csvg id='Layer_1' data-name='Layer 1' xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16'%3E%3Crect fill='%23ffffff' x='5.68' y='6.93' width='2.1' height='6.1' rx='0.96' transform='translate(-1.94 1.63) rotate(-12.09)'/%3E%3Cpath fill='%2303edf9' d='M7.08,13.5a1.46,1.46,0,0,1-1.43-1.16L4.77,8.26A1.47,1.47,0,0,1,5.9,6.53l.17,0A1.46,1.46,0,0,1,7.81,7.61l.87,4.09a1.46,1.46,0,0,1-1.12,1.73l-.18,0Zm-.7-6h-.1l-.17,0a.45.45,0,0,0-.29.21.45.45,0,0,0-.07.34l.88,4.09a.46.46,0,0,0,.54.35l.18,0a.46.46,0,0,0,.29-.2.48.48,0,0,0,.07-.35L6.83,7.82A.46.46,0,0,0,6.38,7.46Z'/%3E%3Crect fill='%23ffffff' x='8.22' y='6.93' width='2.1' height='6.1' rx='0.96' transform='translate(16.25 21.68) rotate(-167.91)'/%3E%3Cpath fill='%2303edf9' d='M8.93,13.5a1.63,1.63,0,0,1-.31,0l-.18,0A1.46,1.46,0,0,1,7.32,11.7l.87-4.09A1.47,1.47,0,0,1,9.93,6.49l.18,0a1.45,1.45,0,0,1,.92.63,1.47,1.47,0,0,1,.2,1.1l-.88,4.08a1.45,1.45,0,0,1-.63.93A1.48,1.48,0,0,1,8.93,13.5Zm.69-6a.45.45,0,0,0-.25.07.5.5,0,0,0-.2.29L8.3,11.9a.43.43,0,0,0,.06.35.46.46,0,0,0,.29.2l.18,0a.47.47,0,0,0,.55-.35l.87-4.09a.45.45,0,0,0-.06-.34A.47.47,0,0,0,9.9,7.5l-.18,0Z'/%3E%3Cpath fill='%23ffffff' d='M11.77,9l-3.53.67a1,1,0,0,1-1.15-.88h0A1.09,1.09,0,0,1,7.9,7.48l3.53-.67a1,1,0,0,1,1.15.89h0A1.08,1.08,0,0,1,11.77,9Z'/%3E%3Cpath fill='%2303edf9' d='M8.07,10.18A1.54,1.54,0,0,1,6.6,8.83a1.74,1.74,0,0,1,.25-1.22,1.46,1.46,0,0,1,1-.66l3.52-.67A1.51,1.51,0,0,1,13.07,7.6a1.61,1.61,0,0,1-1.22,1.88l-3.52.67A1.15,1.15,0,0,1,8.07,10.18ZM11.6,7.34h-.09L8,8a.53.53,0,0,0-.4.62.5.5,0,0,0,.57.44l3.52-.67a.54.54,0,0,0,.41-.62A.53.53,0,0,0,11.6,7.34Z'/%3E%3Cpath fill='%23ffffff' d='M11.74,6.74,4.67,8.08A1,1,0,0,1,3.52,7.2h0A1.08,1.08,0,0,1,4.33,6l7.06-1.34a1,1,0,0,1,1.16.88h0A1.08,1.08,0,0,1,11.74,6.74Z'/%3E%3Cpath fill='%2303edf9' d='M4.5,8.64a1.44,1.44,0,0,1-.86-.29A1.64,1.64,0,0,1,3,7.29a1.72,1.72,0,0,1,.25-1.21,1.48,1.48,0,0,1,1-.67l7.07-1.34a1.39,1.39,0,0,1,1.11.27A1.65,1.65,0,0,1,13,5.4a1.72,1.72,0,0,1-.25,1.21,1.48,1.48,0,0,1-1,.67L4.76,8.62Zm7.07-3.5h-.09L4.42,6.49a.45.45,0,0,0-.32.22.56.56,0,0,0-.09.4.61.61,0,0,0,.21.35.47.47,0,0,0,.36.09L11.65,6.2A.47.47,0,0,0,12,6a.51.51,0,0,0,.08-.4.55.55,0,0,0-.2-.35A.47.47,0,0,0,11.57,5.14Z'/%3E%3Cpath fill='%23ffffff' d='M11.7,4.52,4.64,5.86A1,1,0,0,1,3.49,5h0A1.09,1.09,0,0,1,4.3,3.72l7.06-1.34a1,1,0,0,1,1.15.88h0A1.09,1.09,0,0,1,11.7,4.52Z'/%3E%3Cpath fill='%2303edf9' d='M4.46,6.42a1.36,1.36,0,0,1-.85-.3,1.58,1.58,0,0,1-.61-1A1.61,1.61,0,0,1,4.21,3.19l7.07-1.34a1.35,1.35,0,0,1,1.11.27,1.58,1.58,0,0,1,.61,1,1.74,1.74,0,0,1-.25,1.22,1.44,1.44,0,0,1-1,.66L4.72,6.39A1.09,1.09,0,0,1,4.46,6.42Zm7.07-3.51h-.08L4.38,4.26a.53.53,0,0,0-.4.62.5.5,0,0,0,.57.44L11.62,4a.47.47,0,0,0,.32-.22.62.62,0,0,0,.08-.4.56.56,0,0,0-.2-.35A.53.53,0,0,0,11.53,2.91Z'/%3E%3Cpath fill='%23ffffff' d='M8.34,2.89,4.57,3.6a1,1,0,0,1-1.15-.88h0a1.08,1.08,0,0,1,.81-1.25L8,.75a1,1,0,0,1,1.15.89h0A1.08,1.08,0,0,1,8.34,2.89Z'/%3E%3Cpath fill='%2303edf9' d='M4.4,4.16a1.44,1.44,0,0,1-.86-.29,1.69,1.69,0,0,1-.61-1.05A1.74,1.74,0,0,1,3.18,1.6a1.51,1.51,0,0,1,1-.67L7.91.22A1.38,1.38,0,0,1,9,.49a1.58,1.58,0,0,1,.61,1.05,1.74,1.74,0,0,1-.25,1.22,1.47,1.47,0,0,1-1,.66l-3.77.72A1.18,1.18,0,0,1,4.4,4.16ZM8.17,1.28H8.09L4.32,2A.45.45,0,0,0,4,2.23a.51.51,0,0,0-.08.4.55.55,0,0,0,.2.35.49.49,0,0,0,.37.09l3.77-.72a.47.47,0,0,0,.32-.22.62.62,0,0,0,.08-.4.56.56,0,0,0-.2-.35A.53.53,0,0,0,8.17,1.28Z'/%3E%3Cpolygon fill='%231e1e1e' points='5.5 11.1 5.5 11.1 5.5 14.4 7.1 16 9.1 16 10.6 14.4 10.6 11.1 5.5 11.1'/%3E%3Cpath fill='%23c5c5c5' d='M6.5,12h3v1h-3Zm1,3H8.6l.9-1h-3Z'/%3E%3C/svg%3E") 50% no-repeat !important;
  filter: drop-shadow(0 0 5px #03edf9);
}

.codicon-lightbulb-autofix:before, 
.codicon-light-bulb:before, .codicon-lightbulb:before {
  content: '' !important;
  background:  url("data:image/svg+xml,%3Csvg id='Layer_1' data-name='Layer 1' xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16'%3E%3Crect fill='%23ffffff' x='5.68' y='6.93' width='2.1' height='6.1' rx='0.96' transform='translate(-1.94 1.63) rotate(-12.09)'/%3E%3Cpath fill='%2303edf9' d='M7.08,13.5a1.46,1.46,0,0,1-1.43-1.16L4.77,8.26A1.47,1.47,0,0,1,5.9,6.53l.17,0A1.46,1.46,0,0,1,7.81,7.61l.87,4.09a1.46,1.46,0,0,1-1.12,1.73l-.18,0Zm-.7-6h-.1l-.17,0a.45.45,0,0,0-.29.21.45.45,0,0,0-.07.34l.88,4.09a.46.46,0,0,0,.54.35l.18,0a.46.46,0,0,0,.29-.2.48.48,0,0,0,.07-.35L6.83,7.82A.46.46,0,0,0,6.38,7.46Z'/%3E%3Crect fill='%23ffffff' x='8.22' y='6.93' width='2.1' height='6.1' rx='0.96' transform='translate(16.25 21.68) rotate(-167.91)'/%3E%3Cpath fill='%2303edf9' d='M8.93,13.5a1.63,1.63,0,0,1-.31,0l-.18,0A1.46,1.46,0,0,1,7.32,11.7l.87-4.09A1.47,1.47,0,0,1,9.93,6.49l.18,0a1.45,1.45,0,0,1,.92.63,1.47,1.47,0,0,1,.2,1.1l-.88,4.08a1.45,1.45,0,0,1-.63.93A1.48,1.48,0,0,1,8.93,13.5Zm.69-6a.45.45,0,0,0-.25.07.5.5,0,0,0-.2.29L8.3,11.9a.43.43,0,0,0,.06.35.46.46,0,0,0,.29.2l.18,0a.47.47,0,0,0,.55-.35l.87-4.09a.45.45,0,0,0-.06-.34A.47.47,0,0,0,9.9,7.5l-.18,0Z'/%3E%3Cpath fill='%23ffffff' d='M11.77,9l-3.53.67a1,1,0,0,1-1.15-.88h0A1.09,1.09,0,0,1,7.9,7.48l3.53-.67a1,1,0,0,1,1.15.89h0A1.08,1.08,0,0,1,11.77,9Z'/%3E%3Cpath fill='%2303edf9' d='M8.07,10.18A1.54,1.54,0,0,1,6.6,8.83a1.74,1.74,0,0,1,.25-1.22,1.46,1.46,0,0,1,1-.66l3.52-.67A1.51,1.51,0,0,1,13.07,7.6a1.61,1.61,0,0,1-1.22,1.88l-3.52.67A1.15,1.15,0,0,1,8.07,10.18ZM11.6,7.34h-.09L8,8a.53.53,0,0,0-.4.62.5.5,0,0,0,.57.44l3.52-.67a.54.54,0,0,0,.41-.62A.53.53,0,0,0,11.6,7.34Z'/%3E%3Cpath fill='%23ffffff' d='M11.74,6.74,4.67,8.08A1,1,0,0,1,3.52,7.2h0A1.08,1.08,0,0,1,4.33,6l7.06-1.34a1,1,0,0,1,1.16.88h0A1.08,1.08,0,0,1,11.74,6.74Z'/%3E%3Cpath fill='%2303edf9' d='M4.5,8.64a1.44,1.44,0,0,1-.86-.29A1.64,1.64,0,0,1,3,7.29a1.72,1.72,0,0,1,.25-1.21,1.48,1.48,0,0,1,1-.67l7.07-1.34a1.39,1.39,0,0,1,1.11.27A1.65,1.65,0,0,1,13,5.4a1.72,1.72,0,0,1-.25,1.21,1.48,1.48,0,0,1-1,.67L4.76,8.62Zm7.07-3.5h-.09L4.42,6.49a.45.45,0,0,0-.32.22.56.56,0,0,0-.09.4.61.61,0,0,0,.21.35.47.47,0,0,0,.36.09L11.65,6.2A.47.47,0,0,0,12,6a.51.51,0,0,0,.08-.4.55.55,0,0,0-.2-.35A.47.47,0,0,0,11.57,5.14Z'/%3E%3Cpath fill='%23ffffff' d='M11.7,4.52,4.64,5.86A1,1,0,0,1,3.49,5h0A1.09,1.09,0,0,1,4.3,3.72l7.06-1.34a1,1,0,0,1,1.15.88h0A1.09,1.09,0,0,1,11.7,4.52Z'/%3E%3Cpath fill='%2303edf9' d='M4.46,6.42a1.36,1.36,0,0,1-.85-.3,1.58,1.58,0,0,1-.61-1A1.61,1.61,0,0,1,4.21,3.19l7.07-1.34a1.35,1.35,0,0,1,1.11.27,1.58,1.58,0,0,1,.61,1,1.74,1.74,0,0,1-.25,1.22,1.44,1.44,0,0,1-1,.66L4.72,6.39A1.09,1.09,0,0,1,4.46,6.42Zm7.07-3.51h-.08L4.38,4.26a.53.53,0,0,0-.4.62.5.5,0,0,0,.57.44L11.62,4a.47.47,0,0,0,.32-.22.62.62,0,0,0,.08-.4.56.56,0,0,0-.2-.35A.53.53,0,0,0,11.53,2.91Z'/%3E%3Cpath fill='%23ffffff' d='M8.34,2.89,4.57,3.6a1,1,0,0,1-1.15-.88h0a1.08,1.08,0,0,1,.81-1.25L8,.75a1,1,0,0,1,1.15.89h0A1.08,1.08,0,0,1,8.34,2.89Z'/%3E%3Cpath fill='%2303edf9' d='M4.4,4.16a1.44,1.44,0,0,1-.86-.29,1.69,1.69,0,0,1-.61-1.05A1.74,1.74,0,0,1,3.18,1.6a1.51,1.51,0,0,1,1-.67L7.91.22A1.38,1.38,0,0,1,9,.49a1.58,1.58,0,0,1,.61,1.05,1.74,1.74,0,0,1-.25,1.22,1.47,1.47,0,0,1-1,.66l-3.77.72A1.18,1.18,0,0,1,4.4,4.16ZM8.17,1.28H8.09L4.32,2A.45.45,0,0,0,4,2.23a.51.51,0,0,0-.08.4.55.55,0,0,0,.2.35.49.49,0,0,0,.37.09l3.77-.72a.47.47,0,0,0,.32-.22.62.62,0,0,0,.08-.4.56.56,0,0,0-.2-.35A.53.53,0,0,0,8.17,1.28Z'/%3E%3Cpolygon fill='%231e1e1e' points='5.5 11.1 5.5 11.1 5.5 14.4 7.1 16 9.1 16 10.6 14.4 10.6 11.1 5.5 11.1'/%3E%3Cpath fill='%23c5c5c5' d='M6.5,12h3v1h-3Zm1,3H8.6l.9-1h-3Z'/%3E%3C/svg%3E") 50% no-repeat !important;
  filter: drop-shadow(0 0 5px #03edf9);
  width: 1em;
  height: 1em;
  display: inline-block
}`
