### ISSUE TITLE
Light Bulb svg not working

### ISSUE THREAD

**Issue by MattJett-EWU** [robb0wen/synthwave-vscode#122]
Hi, I could he wrong but I think the theme's light bulb should be something different aside from a normal yellow light bulb. I can't seem to find a screenshot of what the default synthwave '84 theme has for a value in the lightbulb css class. I copied the current code for the bulb listed in the repository here, but still seeing a yellow bulb. Am I doing this right or am I imaging things. Can anyone confirm with what their light bulb icon looks like?

**Comment by robb0wen** [comment]
Vs code changed the lightbulb CSS entirely to use an icon font. I've updated the cas for the upcoming v0.1.0 release
