### ISSUE TITLE
Not working in VSCode 1.41.1

### ISSUE THREAD

**Issue by ezequias** [robb0wen/synthwave-vscode#123]
I just updated my code, reinstalled the two extensions and it still not working.

Have any of you experienced something like this I am experiencing?

Summary VS Code installation:
Version: 1.41.1 (user setup)
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17763

--
Best regards
Ezequias Rocha

**Comment by robb0wen** [comment]
Hi! There's already an open issue here #118 and there's a patch you can apply to fix it too https://github.com/robb0wen/synthwave-vscode/issues/118#issuecomment-565839694

I'm also working on a new version that doesn't need any separate extensions that will solve the issue longer term.

**Comment by ezequias** [comment]
I got the solution. I was trying to create a settings.json in my workspace but the settings.json that was mentioned is the **File > Preferences > Settings > User Workbench > Appearance > Edit in settings.json** link in VSCode.

Now it's all ok. 

Nice to know you are improving the Theme. If you want some help just call me in pvt.
