### ISSUE TITLE
Different highlighting syntax after I reopened VSCode

### ISSUE THREAD

**Issue by astronomyf** [robb0wen/synthwave-vscode#126]
I followed the instructions and made things work as expected, but as soon as I closed and reopened the editor after a while my highlighting syntax changed. Here's a screen capture:
![Schermata 2019-12-29 alle 12 56 00](https://user-images.githubusercontent.com/47946866/71556566-ad2b7e80-2a3a-11ea-8f2e-04a2d420c816.png)

HTML syntax but also other languages in general are not being highlighted as they were before. Any ideas?

**Comment by drewtato** [comment]
Things have changed in 1.41.0, see #118

**Comment by SuddenlyPineapple** [comment]
Are there some solutions to fix this? I have the same issue

**Comment by vaaski** [comment]
_[copied from #131]_

please look through the existing issues before opening a new one, I'm pretty sure #118 has the solution you're looking for. try using the css from [here](https://github.com/robb0wen/synthwave-vscode/issues/118#issuecomment-565839694) and see if that solves your problem. in case it does please close this issue.
@SuddenlyPineapple @astronomyf

**Comment by robb0wen** [comment]
The release of v0.10.0 will correct this issue. If you update the extension from VS Code marketplace and follow the instructions in the readme, the colours should go back to how they were.
