### ISSUE TITLE
I did everything，but no glow macOs 10.14.6   code 1.14.1

### ISSUE THREAD

**Issue by dingyu0810** [robb0wen/synthwave-vscode#127]
1.use css and js loader，no glow
![image](https://user-images.githubusercontent.com/40651005/71807002-485ccd80-30a5-11ea-8c16-e65dd680847f.png)
![image](https://user-images.githubusercontent.com/40651005/71807050-63c7d880-30a5-11ea-8d41-d2c145098ce0.png)

2.new version 0.1.0  no glow
![image](https://user-images.githubusercontent.com/40651005/71807163-9bcf1b80-30a5-11ea-876f-4c9603203e41.png)

**Comment by isnifer** [comment]
@dingyu0810 `Ctrl + Shift + P or Shift + ⌘ + P and choose "Enable custom CSS and JS".` not `Neon Dreams`

**Comment by dingyu0810** [comment]
I choosed，it didn't work

**Comment by njvack** [comment]
I had this issue, uninstalled the custom CSS extension, restarted, reinstalled it, restarted, did Shift + ⌘ + P -> Disable custom CSS, Shift + ⌘ + P -> Enable custom CSS, restarted, and all was well. Mixed in there somewhere was putting the custom CSS stuff up at the top of settings.json, though that shouldn't matter.

Not sure what did it, but it did ultimately work. macOS 10.14.6, VS Code 1.41.1.

**Comment by robb0wen** [comment]
Not sure if this issue is still happening, but please try uninstalling your current version of Synthwave '84, and then reinstall the official v0.1.0 release from the marketplace. If you follow the instructions in the readme, you will hopefully get the glow
