### ISSUE TITLE
No glow

### ISSUE THREAD

**Issue by seheraksoy** [robb0wen/synthwave-vscode#131]
Hey, I know you may have read this over and over. I did all the steps but still there is no glow. I copied the exact code and stuff no glow. 
I use the macOS system

**Comment by vaaski** [comment]
please look through the existing issues before opening a new one, I'm pretty sure #118 has the solution you're looking for. try using the css from [here](https://github.com/robb0wen/synthwave-vscode/issues/118#issuecomment-565839694) and see if that solves your problem. in case it does please close this issue.

**Comment by vaaski** [comment]
@robb0wen can you maybe pin #118 to avoid people opening new issues?

**Comment by seheraksoy** [comment]
thank you. will close this issue.
