### ISSUE TITLE
Command Error on ver 1.0

### ISSUE THREAD

**Issue by vecto0r** [robb0wen/synthwave-vscode#133]
Every time i try to use any synthwave84 commands i get this error

![image](https://user-images.githubusercontent.com/24547797/74442778-dcfade00-4e50-11ea-9409-66c96ea785d4.png)

**Comment by robb0wen** [comment]
This happens sometimes when manually installing the extension. I'm about to release v0.1.0 to the marketplace, so this shouldn't be an issue shortly

**Comment by robb0wen** [comment]
Just released, so you can update from the marketplace
