### ISSUE TITLE
Your Code installation appears to be corrupt. Please reinstall

### ISSUE THREAD

**Issue by cosmokid** [robb0wen/synthwave-vscode#139]
Getting this error ever since the latest update. 

`Your Code installation appears to be corrupt. Please reinstall`

occurs when i enable neon dreams

**Comment by NileDaley** [comment]
I get the same message, even after disabling neon dreams and uninstalling the extension. I think the only way to fix will be to re-install vscode.

**Comment by robb0wen** [comment]
This is expected as the extension modifies the core vs code files and Vs code identifies this as being 'corrupt'. As it says in the extension readme, you can dismiss this message or reinstall VS code to revert all changes.

**Comment by robjac** [comment]
@robb0wen when you say reinstall, do you mean just downloading a new app, and replacing the old with the new ( Mac OS ) ?

Does this "corruption" occur in a particular directory, for example `.vscode/extensions` ? 

a simple "normal" reinstall did not fix it for me. 
I had to fully `rm -rf` all traces of vscode, reinstall and resync all my extensions again.

**Comment by sharda-dixit** [comment]
Getting the same error:
"Your Code installation appears to be corrupt. Please reinstall"
even after re-installing VSCode many times.

**Comment by randomrajan** [comment]
I am getting the same error repeatedly even after installing it again. I uninstalled it completely. it didn't work.

**Comment by sharda-dixit** [comment]
> 
> 
> Getting the same error:
> "Your Code installation appears to be corrupt. Please reinstall"
> even after re-installing VSCode many times.

My antivirus was preventing installation of some files.
Solved this by excluding the file extention "JS" in my Quick Heal Security solution.
Now everything is working fine.

**Comment by aidar64kz** [comment]
I just downloaded vscode and installed on top of my already installed vscode, and error is gone

**Comment by joanmassalle-additio** [comment]
@aidar64kz this works for me too

**Comment by mondersky** [comment]
This error message appears because the extension modifies your vs code files directly, this is mentioned in the readme. You can hide the message with this [extension](https://marketplace.visualstudio.com/items?itemName=mondersky.installation-corrupt-remover)
