### ISSUE TITLE
Support 'Operator Mono' font

### ISSUE THREAD

**Issue by dreamyguy** [robb0wen/synthwave-vscode#14]
**Operator Mono** is a beautiful coding font that I've been using for a while, but themes need to provide support for it to get it to display correctly.

I don't know what it takes to get it done but might try getting this done, for fun. 🙂

If anyone knows how to do it and want to have a swing at it, I'd be super happy! 🙌

**Comment by robb0wen** [comment]
I don't own the font myself, but I can take at look at other themes and see how they do it. If not, someone with the font is welcome to have a go at integrating this :)

**Comment by dreamyguy** [comment]
@robb0wen this is great! I got the font, so I can code review the PR.

**Comment by timdeschryver** [comment]
What exactly is wrong? I'm also using operator mono, but I don't encounter any problems.

**Comment by robb0wen** [comment]
The font setting is independent of the theme, but I guess it's the overall use of italics. 

Some themes, such as Cobalt2 have more italics for html attributes etc. The problem is that for people who aren't using operator mono, all the italics can look a bit...weird. 

I think the best solution would be to add a secondary theme variant that has extra italics.

**Comment by JoshAddington** [comment]
Users can set their own italics rules in their `settings.json` file. I don't think it should be up to @robb0wen to set your italics. These are the rules I'm currently using.
```
"editor.tokenColorCustomizations": {
      "textMateRules": [
        {
          "scope": [
            "comment",
            "constant", //String, Number, Boolean…, this, super
            "keyword", //import, export, return…
            "markup.italic",
            "meta.selector",
            "storage.modifier", //static keyword
            "storage.type",
            "storage.type.class.js", //class keyword
            "variable.language",
          ],
          "settings": {
            "fontStyle": "italic",
          }
        },
        {
          "scope": [
            //following will be excluded from italics (VSCode has some defaults for italics)
            "constant.numeric.css",
            "constant.numeric.decimal.js",
            "constant.numeric.json",
            "invalid",
            "keyword.other.unit.px.css"
          ],
          "settings": {
            "fontStyle": ""
          }
        }
      ]
    }
```
