### ISSUE TITLE
Error: Something went wrong when starting neon dreams

### ISSUE THREAD

**Issue by rbrtbrnschn** [robb0wen/synthwave-vscode#143]
# Solution for Linux

### Update & Install wget
> sudo apt update
> sudo apt install software-properties-common apt-transport-https wget

### Import the Microsoft GPG key & Add the repository
> wget -q https://packages.microsoft.com/keys/microsoft.asc -O- | sudo apt-key add -
> sudo add-apt-repository "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"

### Update Again & Install
> sudo apt update
> sudo apt install code

### Open VS Code By:
> sudo code --user-data-dir="~/.vscode-root"
## Tested on:
- ubuntu: 19.10, 18.04
- Mac osx: 10.15.2
- vscode: newest version
*With/without sudo privileges*

**Comment by matiasnoriega** [comment]
What went wrong?

**Comment by batsev** [comment]
I have ubuntu and i was trying to achive the same. Got the same Error in VS Code: "Something went wrong when starting neon dreams"

**Comment by rbrtbrnschn** [comment]
> What went wrong?

No The Error message upon clicking "enable neon dreams" is literally:"Something went wrong when starting neon dreams"
:D

**Comment by evemontalvao** [comment]
Same here 😢

**Comment by WillHernandez** [comment]
When you thought they made it "simple" to glow.. Dam u Ubuntu!!!

**Comment by n1colius** [comment]
same here.. just install and it just wont glow :(
i am on ubuntu 18.04

**Comment by redbeardaz** [comment]
I tried to activate the glow as well.

Now I have the error in VS Code:
>Your Code installation appears to be corrupt. Please reinstall.

**Comment by rbrtbrnschn** [comment]
> I tried to activate the glow as well.
> 
> Now I have the error in VS Code:
> 
> > Your Code installation appears to be corrupt. Please reinstall.

On Linux too?

**Comment by redbeardaz** [comment]
> > I tried to activate the glow as well.
> > Now I have the error in VS Code:
> > > Your Code installation appears to be corrupt. Please reinstall.
> 
> On Linux too?

Mac Catalina (10.15.2)

**Comment by DamirRistic** [comment]
Same here.
On ubuntu 18.04

**Comment by AntonDeXy** [comment]
@redbeardaz @evemontalvao @rbrtbrnschn i had this problem on Mac. I just cut vsCode from folder application to a different folder where i have "read and WRITE" permission (right click => get info => sharing & permissions)

**Comment by DamirRistic** [comment]
I did it!
My VsCode was installed over snap, so i deleted it and installed it again following instructions from this link 
https://linuxize.com/post/how-to-install-visual-studio-code-on-ubuntu-18-04/
After installation i started it as root user, with this command in terminal
sudo code --user-data-dir="~/.vscode-root"
Now i could enable neon dreams
After that just exit VsCode and start it again as regular user and it works

**Comment by rbrtbrnschn** [comment]
Issue Has Been Solved!

**Comment by BharadwajKaranam** [comment]
For Mac, i did the following it worked :
 
Step 1 : Created a new folder with read permissions, move Visual Studio Code app into that folder. 

New Folder : change its permission to read-only (click folder >command+i > Sharing & Permissions >read-only),
VisualStudioCode.app : has read+write permissions (by default).

Then open VSCode > choose the theme > cmd+shift+P > Enable Neon Dreams > It asks you to restart > Restart. 
You should be seeing the glow 👍 .

**Comment by kissu** [comment]
Reminder, before trying the OP's solution, remove `code` if installed w/ snap: `sudo snap remove code`
