### ISSUE TITLE
glow too faint

### ISSUE THREAD

**Issue by rymo** [robb0wen/synthwave-vscode#15]
My editor didn't match the extreme neon awesomeness of the screenshot in readme until I reverted css to commit 71da96f.

Don't question your art, it's beautiful!

**Comment by robb0wen** [comment]
Haha thanks. 

I had several issues raised on twitter about contrast, so decided to improve it across the board. I added a little opacity to the glow in the hopes of increasing usability. 

As the CSS is standalone though, you're free to tweak it how you want 👍
