### ISSUE TITLE
synthwave84: Enable Neon Dreams didn't work

### ISSUE THREAD

**Issue by jasonn0118** [robb0wen/synthwave-vscode#151]
I installed Synthwave 84, and I exited to use amazing theme ever.
Unfortunately it didn’t work the enable function on my Mac.

It kept saying something went wrong when starting neon dreams😔

**Comment by jasonn0118** [comment]
I've solved this problem.
It was caused by permission reason

**Comment by official-rakeshsinha** [comment]
@jasonn0118 How did you do that?
