### ISSUE TITLE
Error after uninstall

### ISSUE THREAD

**Issue by dodalovic** [robb0wen/synthwave-vscode#157]
After trying and deciding to uninstall the theme, I'm getting this every time when I start vscode. 

![image](https://user-images.githubusercontent.com/6358061/76740147-b42a7900-676d-11ea-83f8-ae1f9bf39951.png)

Is there any cure to this? 

Thanks! :)

**Comment by robb0wen** [comment]
You can install this extension to fix the issue https://marketplace.visualstudio.com/items?itemName=lehni.vscode-fix-checksums
