### ISSUE TITLE
Your Code installation appears to be corrupt. Please reinstall.

### ISSUE THREAD

**Issue by adnan-elahi** [robb0wen/synthwave-vscode#159]
everything is working fine but when ever I'm opening vscode showing this message... How to get rid of this?

**Comment by jdubwelch** [comment]
Same with me.

**Comment by robb0wen** [comment]
You can slick the little cog icon on the notification and choose "do not show this again". This message is expected as the neon updates the core files of VS code, which it recognises as being 'corrupted'. Everything will still work fine, but your header bar will say 'unsupported'

**Comment by CruxCv** [comment]
Same with me.

**Comment by Cecile-Lebleu** [comment]
Same here. Neon Dreams keeps turning off, and every time I run "Enable Neon Dreams", that message pops up.
Other than that, it's pretty darn amazing :)

**Comment by Pixelshot** [comment]
Fix VSCode Checksums removed **[unsupported]** from the header bar for me

https://marketplace.visualstudio.com/items?itemName=lehni.vscode-fix-checksums

**Comment by MatrixV01** [comment]
> Fix VSCode Checksums removed **[unsupported]** from the header bar for me
> 
> https://marketplace.visualstudio.com/items?itemName=lehni.vscode-fix-checksums

Worked like a charm. Thank you!

**Comment by robb0wen** [comment]
@Pixelshot That's brilliant. I was unaware that extension existed and it's awesome. I'll update the docs to recommend it. Thanks!!

**Comment by Pixelshot** [comment]
@robb0wen I've included a section for this extension in README.md and made a pull request. Feel free to make use of it however you like. Either way, thank you for this awesome theme!

**Comment by robb0wen** [comment]
Just merged it in 🎉

**Comment by ysh-50** [comment]
> Same here. Neon Dreams keeps turning off, and every time I run "Enable Neon Dreams", that message pops up. Other than that, it's pretty darn amazing :)

but i want that neon theme, how to get it

**Comment by gnujesus** [comment]
> You can click the little cog icon on the notification and choose "do not show this again". This message is expected as the neon updates the core files of VS code, which it recognises as being 'corrupted'. Everything will still work fine, but your header bar will say 'unsupported'

Mine says [WSL: Ubuntu]. I started getting this message when I opened vscode via `code .` on WSL (Ubuntu). I installed it on my machine, opened my WSL, cloned a repository in which I was working before migrating back to windows, and when I ran vscode I got that error. I don't know if I should be worried.

**Comment by mondersky** [comment]
This error message appears because the extension modifies your vs code files directly, this is mentioned in the readme. You can hide the message with this [extension](https://marketplace.visualstudio.com/items?itemName=mondersky.installation-corrupt-remover)
