### ISSUE TITLE
Context/import Menu selection color not visible

### ISSUE THREAD

**Issue by ericj17** [robb0wen/synthwave-vscode#16]
Great theme! I noticed the selected item highlighting is too dark to see. In the screenshot below, the mouse is hovering over an item but the highlighting is very faint.
![image](https://user-images.githubusercontent.com/4195650/56963116-0db19700-6b0d-11e9-9381-3c92626dbace.png)

Similarly, text selection on pop up menus have the same faint highlighting. E.g. some of the text in the pop up below is selected.
![image](https://user-images.githubusercontent.com/4195650/56967904-02636900-6b17-11e9-9619-d7e86ab2a199.png)

Perhaps we could use the highlight color similar to issue #1 ?

Thanks!
Eric

**Comment by robb0wen** [comment]
Thanks for flagging this. I'll look into it
