### ISSUE TITLE
Issue while Enabling neon Dreams on ubuntu 18.04.

### ISSUE THREAD

**Issue by digvijay-r** [robb0wen/synthwave-vscode#160]
On enabling the Neon Dreams It is showing a notification popup in code that you must run vs code with admin priviliges to enable this and the neon dreams isn't enabling.

Here is the attached screenshot.
![Screenshot from 2020-04-05 16-44-46](https://user-images.githubusercontent.com/41992412/78473336-6cd84c80-775d-11ea-8c98-3b34e02dc34b.png)

**Comment by Zzombiee2361** [comment]
It is not recommended to run VS Code as root. I managed to enable it after running these commands:
```bash
sudo chown root:sudo -R /usr/share/code/resources/app/out/
sudo chmod 775 -R /usr/share/code/resources/app/out/
```

**Comment by digvijay-r** [comment]
> It is not recommended to run VS Code as root. I managed to enable it after running these commands:
> 
> ```shell
> sudo chown root:sudo -R /usr/share/code/resources/app/out/
> sudo chmod 775 -R /usr/share/code/resources/app/out/
> ```

Thanks, After running the commands, the issue is resolved.

**Comment by umakanth-pendyala** [comment]
> > It is not recommended to run VS Code as root. I managed to enable it after running these commands:
> > ```shell
> > sudo chown root:sudo -R /usr/share/code/resources/app/out/
> > sudo chmod 775 -R /usr/share/code/resources/app/out/
> > ```
> 
> Thanks, After running the commands, the issue is resolved.

I am getting this message after running the first command

chown: cannot access '/usr/share/code/resources/app/out/': No such file or directory

**Comment by Zzombiee2361** [comment]
@umakanth-pendyala how did you install VS Code? My method only works for native package

**Comment by umakanth-pendyala** [comment]
I use Linux Mint, as usual, I've installed vs code through command line.

**Comment by Zzombiee2361** [comment]
Well, snap and flatpak app can also be installed using command line. If you do install it from repository and it's not installed on `/usr/share/code` then I have no idea where it is

**Comment by umakanth-pendyala** [comment]
Ok, can I reinstall it again from the repo, without losing the extinctions I've installed, cause I've been using this VS code for almost like 10 months now.

**Comment by umakanth-pendyala** [comment]
One more thing, If I could manage to find the location of the vs code, do you think we can make this work.

**Comment by Zzombiee2361** [comment]
Yeah, sure. Just `chown` then `chmod` that folder

**Comment by umakanth-pendyala** [comment]
It's in snap/bin/code

**Comment by umakanth-pendyala** [comment]
I'm sorry, but now I am getting the following message

` chown: cannot access '/snap/bin/code/resources/app/out/': Not a directory`

But I found the path of my vs code through 

`which code`

Then  it showed me snap/bin/code

**Comment by Zzombiee2361** [comment]
It won't work on snap. My method is for native package installed using package manager. It might work on flatpak, you have to find the location though, but it definitely won't work on snap.

**Comment by umakanth-pendyala** [comment]
ok, what is the alternative can I uninstall it and reinstall it again without losing the extinctions.

**Comment by Zzombiee2361** [comment]
You can always backup your config and extensions. I have no idea where it is on snap though, it might be on snap folder on your home. But you have to google how to do it yourself

**Comment by yusuf-delvi** [comment]
@umakanth-pendyala setup [this](https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync) extention all your settings will be on cloud

**Comment by vipulgupta2048** [comment]
The best solution is to reinstall vscode with the deb package, save your settings with Settings Sync and then running these commands
``` 
sudo chown root:sudo -R /usr/share/code/resources/app/out/
sudo chmod 775 -R /usr/share/code/resources/app/out/
```
Then enable neon dreams and then it should be fine. With everything intact.

**Comment by hp77-creator** [comment]
> sudo chown root:sudo -R /usr/share/code/resources/app/out/
> sudo chmod 775 -R /usr/share/code/resources/app/out/

this works perfectly. Thank you so much!

**Comment by HarshalRathore** [comment]
@everyone Following @Zzombiee2361 sense's workaround method for Arch-based users.

you have installed code from AUR if with something like yay so it is most likely present in /opt
```
sudo chown root:sudo -R /opt/visual-studio-code/resources/app/out/
sudo chmod 775 -R /opt/visual-studio-code/resources/app/out/
```
**Note:- Doing this corrupts the official VSCode build. Don't get scared with that Corrupt word it basically means that if you reinstall or update VSCode then you have to again run these 2 commands because all the settings will be changed according to the default VScode build.**

PS:- For those people who can't find the VSCode path in their system try these commands.
```
locate code/resources/app/out/
or 
sudo find / -type d -wholename '*code/resources/app/out*'
```
