### ISSUE TITLE
Feature Request: Breathing Light

### ISSUE THREAD

**Issue by ifsheldon** [robb0wen/synthwave-vscode#161]
I think it will be nice to have breathing-like effect on the glow LOL. There is a parameter `brightness` to tune the light of the glow, but can it change dynamically? Say we apply sin(time) function on it to change the brightness of the glow as time goes.

I like this theme very much, but I have not read the source code, so I don't know the difficulty of the implementation. And I think to do this may cause some efficiency/performance issues.

**Comment by deme3** [comment]
Out of curiosity, I did it. Please note it is based on CSS keyframes and it's mostly unstable.
The breathing effect commences each time a new glowing keyword is added to the code, so, different keywords inserted at different times will glow according to when they were written. Also, my MacBook Air runs very hot while this mod is running. Configuration parameters are `synthwave84.enableBreathing` (boolean), `synthwave84.breathingSpeed` (number, in seconds), `synthwave84.breathingFunction` (string, see description while editing). I'll soon add this to the fork README

**Comment by sladiri** [comment]
I recently debugged a website with high CPU usage and there the mat-progress-bar element ate a lot of CPU if there were many of them. The progress-bar is animated with CSS.
I guess it might be impractical to animate many elements individually.

I found the offending elements quickly using `window.onanimationiteration = console.log`. There were events emitted constantly.

**Comment by deme3** [comment]
Yeah that's the main reason why it's practically non doable in VS Code since the editor is rendered in a webpage. Unless you want seizures, heavy lag and way too high energy consumption of course.

**Comment by robb0wen** [comment]
The glow is achieved with text-shadow but unfortunately, whilst text-shadow can be animated with CSS, it triggers both a layout and paint cycle on the browser (https://csstriggers.com/text-shadow)

There are ways around this in a normal website context but, as mentioned above, the number of elements in the editor that would need to be constantly repainted would cause a performance bottleneck.
