### ISSUE TITLE
Something is wrong with the style on activity bar

### ISSUE THREAD

**Issue by Fidaj** [robb0wen/synthwave-vscode#162]
Hello, after updating VS Code the border on the left-hand-side on active items has changed. It acts weird when you switch between the active items. I was wondering if it's some bug or it's intended. 
I hope for your help!

![b403f83324b5e267227716531f57bb44](https://user-images.githubusercontent.com/57771443/79273355-28f2ef00-7ea3-11ea-9aef-4c3bab7794ee.gif)

**Comment by robb0wen** [comment]
I've just pushed a patch to fix this issue. The weird white flash is something VS code does on all themes now, and I haven't quite gotten to the bottom of why

**Comment by Fidaj** [comment]
I see, thank you very much for the response!
