### ISSUE TITLE
Change color of C placeholders

### ISSUE THREAD

**Issue by moxwel** [robb0wen/synthwave-vscode#165]
In other VSCode themes, the C placeholders (like `%i`, `%d`, `%p`, etc) have a different color, it helps to identify them in a string.

In this theme, are almost the same color.

![Anotación 2020-04-25 161239](https://user-images.githubusercontent.com/49621788/80290243-1930a180-8712-11ea-99bd-9dfe06359549.png)

It would be nice to have them in a different color, like the `\n` character.

**Comment by robb0wen** [comment]
Thanks! I've merged it in
