### ISSUE TITLE
Problem in VUE files

### ISSUE THREAD

**Issue by edarblanco** [robb0wen/synthwave-vscode#173]
Hello, excellent theme, I love it but I have noticed that it does not manage the .vue files well, it treats them as a mere javascript file, especially in the template and style sections, try other themes and everything would be fine only with this happens to me , I leave examples of commented code with the topic
![image](https://user-images.githubusercontent.com/3819778/83268868-3be02b00-a194-11ea-8f56-079d7c0f4eba.png)
![image](https://user-images.githubusercontent.com/3819778/83268913-4d293780-a194-11ea-97c5-9e14cd1a048d.png)

**Comment by robb0wen** [comment]
Interesting - I'm a Vue developer myself and I haven't noticed any issues. Which version of the extension are you using, and do you have any custom css?

**Comment by edarblanco** [comment]
Ah nope, I don't have custom style sheets, and my version is 0.1.5, thanks for everything

**Comment by edarblanco** [comment]
fix with version 0.1.8
