### ISSUE TITLE
editor.rulers of settings.json is not compatible with synthwave-vscode

### ISSUE THREAD

**Issue by xiaorong61** [robb0wen/synthwave-vscode#174]
editor.rulers of settings.json is not compatible with synthwave-vscode
![image](https://user-images.githubusercontent.com/5251387/85250226-8cdbfa00-b488-11ea-9f9b-343907298ca6.png)
![image](https://user-images.githubusercontent.com/5251387/85250293-b432c700-b488-11ea-8eb0-1a5cd18643d3.png)

**Comment by moxwel** [comment]
Thanks. The fix is added to pull request #172. Now we just have to wait for the owner to merge the commits.
