### ISSUE TITLE
Glow activation is random or not working

### ISSUE THREAD

**Issue by dominiquediotte** [robb0wen/synthwave-vscode#177]
When using the extension on my Mac, there are moments where I'm not able to see the glow. I tried reloading the window in the command palette, activating the glow again, force quitting the app and reopening it, but nothing is working so far. To add more weirdness, sometimes it works, but it's rare. The theme itself is working. I'm using the latest version. No error messages are showing to me. Btw, the extension looks great, I'm looking to use it daily :)

Here are the infos of VS Code:
Version: 1.47.0
Commit: d5e9aa0227e057a60c82568bf31c04730dc15dcd
Date: 2020-07-09T08:01:54.115Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0

**Comment by robb0wen** [comment]
Yeah, the latest version of VS code has changed the editor boot process which means that the hook Synthwave uses to initialise the glow doesn't always fire in the same order. I'll look into and release a new version as soon as I'm able.

**Comment by robb0wen** [comment]
I've just release v0.1.6 to the VS code marketplace that will fix this issue and also reinstates the neon autofix lightbulb

**Comment by dominiquediotte** [comment]
Thanks for the quick response! The issue is now resolved.
