### ISSUE TITLE
Pinned active tab, that is not the first tab bug

### ISSUE THREAD

**Issue by mattmogford** [robb0wen/synthwave-vscode#182]
When pinning multiple tabs, any tab after the first that becomes active jumps right by the tab width.
This leaves a gap and overlaps the following tab.

Pull request already done - #181 

![Screenshot 2020-07-23 at 11 01 41](https://user-images.githubusercontent.com/2421265/88274617-e62b8900-ccd3-11ea-9e50-27893401a227.png)

**Comment by robb0wen** [comment]
Solved as of v0.1.7 😀
