### ISSUE TITLE
Support Semantic Highlighting

### ISSUE THREAD

**Issue by TylerLeonhardt** [robb0wen/synthwave-vscode#186]
Since 1.43, VSCode themes can take advantage of semantic highlighting.

Every theme controls whether semantic tokens are enabled. So far, only built-in themes have it enabled and I filed this issue to ask you to opt-in for the SynthWave '84 theme as well.

Adoption is easy and there are new cool styling possibilities.

To turn on semantic highlighting for you theme, all you have to do is put
`"semanticHighlighting": true`
in the theme definition file.

There's a good chance that no further change to the theme is needed (thanks to a default mapping from semantic tokens to TextMate scopes (if not, I'd be interested to know, so I can improve the defaults further)). 

But, more interestingly, themes can tune and go wild by defining new styling rules against the semantic tokens:
```json
"semanticTokenColors": {
    "variable.readonly": "#ff0000", 
    "parameter": { "fontStyle": "underline" },
    "*.declaration:java": { "fontStyle": "bold" }
} 
```

Check out our [Semantic Highlighting Wiki](https://github.com/microsoft/vscode/wiki/Semantic-Highlighting-Overview) and the [Semantic Highlighting Guide](https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide) for more details and feel free to ping me in this issue if I can help.

I shamelessly copied this from https://github.com/PowerShell/vscode-powershell/issues/2656

**Comment by robb0wen** [comment]
Added in v0.1.8 :)
