### ISSUE TITLE
Remove line highlight border?

### ISSUE THREAD

**Issue by francisceril** [robb0wen/synthwave-vscode#190]
<img width="587" alt="Screen Shot 2020-08-26 at 7 28 07 PM" src="https://user-images.githubusercontent.com/5759665/91330613-5c8b4180-e7d2-11ea-9b6a-7b0883a565a8.png">

What's the setting to remove the border of a selected line and just make it as background-color?

**Comment by moxwel** [comment]
The border on the active line is intentional, is part of the theme now.

If you want, you can _override_ the color customization of the theme within `settings.json` by adding this:

```
"workbench.colorCustomizations": {
  "[SynthWave '84]": {
    "editor.lineHighlightBackground": "#7059AB45",
    "editor.lineHighlightBorder": "#00000000"
  }
}
```

That will make the border transparent and put color on background.
