### ISSUE TITLE
Activating glow effect immediately corrupts VSCode Installation on MacOS

### ISSUE THREAD

**Issue by ReagentX** [robb0wen/synthwave-vscode#194]
On a fresh install of VSCode, install only this extension. After running `Enable Neon Dreams` VSCode notifies the user that the installation is corrupt and must be reinstalled.

**Comment by ReagentX** [comment]
I see there are other issues that mention this, but you should probably warn the user when they run the command.

**Comment by TahaCoder43** [comment]
This is actually true and this also happened to me, I installed VSCode 4 times because of it

**Comment by dendihandian** [comment]
It's also happening in Windows,

![image](https://user-images.githubusercontent.com/16485031/203559897-3da145ab-42e1-43e5-86ba-ba151c6a4585.png)

![image](https://user-images.githubusercontent.com/16485031/203560115-5bee6675-30f4-455b-b040-956c64f61203.png)
