### ISSUE TITLE
Cannot enable neon dreams on Mac OSx Big Sur

### ISSUE THREAD

**Issue by d4nielhdz** [robb0wen/synthwave-vscode#208]
Getting the error `Something went wrong when starting neon dreams` when trying to enable neon Dreams after opening VS Code with sudo.

**Comment by jomurgel** [comment]
I had the same issue which seemed to be a result of some issues with Big Sur permissions and VSCode. I also received an issue (which seemed to be related) when looking for updates.

I followed [this suggestion](https://github.com/microsoft/vscode/issues/7426#issuecomment-425093469) (the first command returned no results for me, but the second command ran fine), restarted VSCode, and was able to enable Neon Dreams and check for updates.

**Comment by d4nielhdz** [comment]
Thanks! That did it for me.

**Comment by sepehrafiei** [comment]
I had this issue just now. All I had to do was move Visual Studio Code from my downloads folder to Applications and restart it.

Hope it helps.

**Comment by wealthczarena** [comment]
likewise! the first line didn`t work for me but the second did.
