### ISSUE TITLE
IntelliJ Support?

### ISSUE THREAD

**Issue by varrix** [robb0wen/synthwave-vscode#209]
Are there any plans to support IntelliJ? Absolutely love the theme (specifically with glow enabled) and would love to see this on IntelliJ.

I didn't see any other issues mentioning IntelliJ, sorry if it has been asked before.

**Comment by robb0wen** [comment]
Unfortunately I don't think IntelliJ supports CSS on themes (technically neither does VS code) so I don't know how feasible it would be.

I'm happy if anyone else can figure out how to do it though, and I'll link back from this repo if it happens.
