### ISSUE TITLE
"What's New with Synthwave '84" page opens with each new window

### ISSUE THREAD

**Issue by queenkjuul** [robb0wen/synthwave-vscode#217]
I apologize if this is not a Synthwave issue and is a VSCode issue, but it is only happening with this one theme and I have tried everything I can think of to get rid of it, and am at my wit's end. 

Per title, every new window I open causes the "What's New with Synthwave '84" tab to open. However, the actual What's New page never renders, it's just a blank tab. It opens about 2 seconds after the window is open. 

I have completely uninstalled Code, removed all my Code config directories, reinstalled Code, and reinstalled the theme. The issue persisted. I am not sure what else to do. I tried clearing Editor history from the command palette and that did not work, either.

**Comment by dezren39** [comment]
This issue is occuring for me as well. It is entirely blank and I can't crtl+w close it either I have to click, annoying. If I open palette and launch whats new, i get the real thing

**Comment by THEaustinlopez** [comment]
I have been experiencing this for a few months now. I have just been closing the tab but it is starting to get to me. Any fix on this yet?

**Comment by rsamhollyer** [comment]
This issue started happening to me yesterday. I was reinstalling the theme and trying to enable the Neon Dreams color on Fedora, which I tried to do from `[#138 ](https://github.com/robb0wen/synthwave-vscode/issues/138#issuecomment-590111809l)`.  I could never enable the color change, but when I reverted back to the root ownership, this open tab issue began to occur.

**Comment by bobmagicii** [comment]
yes this is now my daily life on all my computers

![image](https://user-images.githubusercontent.com/881944/129788026-1aa20706-47d3-480f-8d62-29a0ba6c1e90.png)

**Comment by bobmagicii** [comment]
fix for people going insane:

%CodeProfilePath%\extensions\robbowen.synthwave-vscode-0.1.8\src\extension.js

add a return after `function showUpdatePage() {`

![image](https://user-images.githubusercontent.com/881944/129788914-e67e0fa8-b31d-49b1-9196-97620fca954f.png)

**Comment by THEaustinlopez** [comment]
You are a lifesaver!!! Thank you so much!!!!

**Comment by trevor-coleman** [comment]
I created this PR which should address the issue:
https://github.com/robb0wen/synthwave-vscode/pull/234

The app currently displays the webview and then updates the stored "previous version."

This means that if the webview fails, the version is never updated.

My PR simply reverses the order of the commands, so that a webview failure won't cause the update page to be displayed forever.

**Comment by yan-levy** [comment]
Thank yooou!!!! I was going crazy really bad

**Comment by robb0wen** [comment]
This page has been removed from v0.1.9

**Comment by HydraCOREY** [comment]
@robb0wen 
The page is still showing up for me. 
I'm on `v0.1.9`.
I've tried uninstalling, reinstalling, manually removing (also rebooting vscode for each).

**Comment by louisoftokyo** [comment]
@robb0wen Still occurring in v0.1.10.

**Comment by RPainter8West** [comment]
Uninstalling the "Dark Synthwave" plugin fixed the problem for me. Thanks for the tip @louisoftokyo

**Comment by rlmorrison74** [comment]
Oh my god thank you so much @louisoftokyo @RPainter8West I have been going insane trying to get rid of this, I haven't even used the synthwave theme since november, I found one I like much better, but this page has been driving me up a wall. Uninstalling Dark synthwave 84 fixed it for me too.

**Comment by milan2sky** [comment]
After some time you start to accept this bug as a feature.
I smile every time when it appears so please do **NOT** fix that!
