### ISSUE TITLE
Abandoned extension/repo?

### ISSUE THREAD

**Issue by darthrodolfo** [robb0wen/synthwave-vscode#218]
I'm having trouble with the message (Your code installation appears to be corrupt. Please reinstall.) And I came here for more information about this bug and so on.

I'm seeing a lot of issues, and pull request that are abandoned for many months. Be careful using this extension.

Also be careful, even reinstalling VsCode it will keep popping message about corrupt installation. I saw some guys commenting about it, and Its "nothing" to worry because this extension changes core files. 

https://github.com/robb0wen/synthwave-vscode/issues/139

They closed it, but didn't mention anything on readme and other places, so user on your own luck. 

PS: I know that I can dismiss this message, but we have to alert other people that looks like there's no one watching, merging, taking care of this. They don't talk about the primary issue and bug with the extension on readme. Suspicious.

**Comment by daniel-liuzzi** [comment]
From the [README](https://github.com/robb0wen/synthwave-vscode#to-remove-corruption-warning-and-unsupported-from-title-bar):

> ### To remove corruption warning and [unsupported] from title-bar
>
> Because enabling the glow modifies core files, VS code will interpret this as the core being 'corrupted' and you may see an error message on restarting your editor. You can safely dismiss this message, or remove it entirely with the [Fix VSCode Checksums](https://marketplace.visualstudio.com/items?itemName=lehni.vscode-fix-checksums 'Fix VSCode Checksums') extension.
>
>Upon installation of 'Fix VSCode Checksums', open the command palette and execute `Fix Checksums: Apply`. You will need to completely restart VSCode after execution, reopening without fully exiting might not be enough.

**Comment by robb0wen** [comment]
Hey! The theme isn't abandoned, but I have a full time job that doesn't give me a lot of time to work it. Until VS code properly implements CSS in themes, there's not a lot else that can be done about this warning message.

The way the extension works is, and has always been, a workaround to the lack of CSS support in VS code themes. As the commenter above kindly mentioned, the readme explains how to fix the error message and also clearly says that the theme is experimental. Unfortunately the whole thing being a workaround means that, as much as I wish it weren't the case, there are many things that could cause problems and near impossible to provide support for every individual setup.

I'm hoping that VS code do implement CSS on themes at some point so this theme can be moved into more official channels, but until then it's very much updated as and when I can.

**Comment by darthrodolfo** [comment]
Wow Sorry for my words robb0wen I was a little angry. Thank you for sharing
your work and extention with the world.

I will try to contribute somehow to help you in some way I can.

I didnt see any update on the last months, also we had some pull request of
long dates. So I looks like that anybody was moving stuff around.

Best wishes, stay healthy.
