### ISSUE TITLE
How i force the use for another language

### ISSUE THREAD

**Issue by fornazierr** [robb0wen/synthwave-vscode#22]
I'm wanna use this theme with rust lang, and i want to know if it's possible to do any method.

**Comment by robb0wen** [comment]
It should be possible. The theme itself has generic styling for most languages. If you have a Rust syntax extension installed, it should work. I can't vouch for how it will style though, because I'm not familiar with Rust

**Comment by fornazierr** [comment]
Look pretty !

[Link](http://prntscr.com/niutsr)
