### ISSUE TITLE
"Your VSCodium installation appears to be corrupt."

### ISSUE THREAD

**Issue by greenfox1505** [robb0wen/synthwave-vscode#23]
![image](https://user-images.githubusercontent.com/1642297/56990956-1b423d80-6b5c-11e9-9b42-a3f150af18ea.png)

After activating the CSS through the Custom CSS and JS Loader pluggin and running "Enable Custom CSS and JS", booting VSCodium gives me this error. I don't know if this occurs on VSCode or if it's a bug within VSCode/VSCodium itself.

Running "Disable Custom CSS and JS" fixes the problem.

**Comment by robb0wen** [comment]
This is a side-effect of the custom CSS plugin as detailed on their installation page https://marketplace.visualstudio.com/items?itemName=be5invis.vscode-custom-css.

It isn't actually corrupted, and you can dismiss the message.

**Comment by zebapy** [comment]
I'm getting this error and never added the custom css plugin.

**Comment by fibric** [comment]
I get the same error now since I enabled Neon Dreams 0.10. I also never installed nor used custom CSS plugin. The error message also appears when I disable Neon Dreams and restart VSCode.

**Comment by shanedg** [comment]
I didn't expect that enabling neon dreams would "corrupt" my vscode install. The v0.10 release notes mention this but the readme is less clear about it. I'm sure the internal change is minor and not unsafe, but feels like this side-effect should be more obvious.

**Comment by DRD161** [comment]
I'm having the same problem. I read [here](https://github.com/spikespaz/vscode-smoothtype/issues/3) that this can be caused by extensions modifying the index file. Wonder if this is the case for Neon Dream? Does the extension modify the index file behind the scenes by chance?  🤔
