### ISSUE TITLE
Always show on start up that what's new in SynthWave '84 Theme when VS Code Open

### ISSUE THREAD

**Issue by kevin-patel** [robb0wen/synthwave-vscode#231]
Issue Type: <b>Bug</b>

Whenever I start VS Code it always show tab that what's new in SynthWave '84 there is no update from thier side neither nor I have opened it for any time, I tried reinstalling the theme as well as vs code still problem exist.

Extension version: 0.1.8
VS Code version: Code - Insiders 1.60.0-insider (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:40:58.134Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.93GB (5.43GB free)|
|Process Argv|--crash-reporter-id 868335f8-f116-482e-b782-0306ddf34e3e|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by JuniorAlvesbr** [comment]
Do this with me too

**Comment by trevor-coleman** [comment]
Same! Super annoying.

Suggest adding an option: 

```json
{
  "synthwave-vscode.showUpdatesOnStartup": false  
}
```

 or something

**Comment by trevor-coleman** [comment]
See also this PR: https://github.com/robb0wen/synthwave-vscode/pull/232

**Comment by HydraCOREY** [comment]
+1
Very annoying. Even uninstalled the extension and it still shows up for me.

**Comment by robb0wen** [comment]
This page has been removed from v0.1.9

**Comment by HydraCOREY** [comment]
Still showing up for me after v0.1.9
![image](https://user-images.githubusercontent.com/15674865/135666671-1ca25436-a29b-4a85-bcf6-f307ac8e5887.png)
