### ISSUE TITLE
Command 'Synthwave '84: Enable Neon Dreams' resulted in an error (command 'synthwave84.enableNeon' not found.

### ISSUE THREAD

**Issue by TylerJaacks** [robb0wen/synthwave-vscode#235]
![Code_qmgdI5xtG9](https://user-images.githubusercontent.com/1505374/133865640-c14adccf-15d2-4650-b7ad-8ff695a23d04.png)

**Comment by capex** [comment]
I had the same problem on Mac today.

**Comment by bernardocrodrigues** [comment]
Same on Linux :(

**Comment by sagrath23** [comment]
Same on VSCode Version: 1.60.1 on Mac

**Comment by aariacarterweir** [comment]
See: https://github.com/robb0wen/synthwave-vscode/issues/222#issuecomment-923682638 for fix

**Comment by Mahdi463** [comment]
> See: [#222 (comment)](https://github.com/robb0wen/synthwave-vscode/issues/222#issuecomment-923682638) for fix

Thanks! it's working now.

**Comment by sagrath23** [comment]
Thanks @aariacarterweir the fix described in #222 works like a charm!

**Comment by gusbdev** [comment]
Thanks @aariacarterweir
