### ISSUE TITLE
Do you know how to package this as an extension?

### ISSUE THREAD

**Issue by jcklpe** [robb0wen/synthwave-vscode#24]
Hey Robb, 

Rad work!

I've also been playing around with using injected CSS and Javascript (and also a bunch of regex based highlighting stuff). And I've been thinking that I'd eventually like to package up my custom crap as an actual extension. I see that you have got stuff wrapped up as a theme. I still need to learn how to do that! How did you do that? (I used Hopscotch theme extension as my starting point and then the rest of my customizations are in my [settings.json](https://github.com/jcklpe/Configs/blob/master/vscode/settings.json) (my injected stuff can also be found [here](https://github.com/jcklpe/Configs/tree/master/vscode/injectedTheme). I went ahead and added your stuff and I'm going to start integrating and tweaking it later. You've done a lot more extensive stuff than I on the injection. I just used the injection stuff to switch fonts in my comments and some other bits and pieces (though I also built stuff up to use a gulp scss build process which I think might be useful as I get more and more complex with my fiddling)) 

And also do you have any idea where one would start if one wanted to take some of the cool hacky bits that you or I have been doing with the injections and integrate them into an actual extension package in a more complete sort of way? 

I've also been adding a bunch of custom syntax highlighting using a regex based highlighting plugin and I wonder if there's some way I could integrate that too?

Also here's a picture of how my hacked theme looks in case you were curious: 

![image](https://user-images.githubusercontent.com/9451726/57001296-83ede200-6b7d-11e9-885d-6219c7baea24.png)

**Comment by robb0wen** [comment]
There's a Yeoman generator for creating the starter framework extensions which you could use (https://code.visualstudio.com/api/get-started/your-first-extension). You'd probably need to write the extension to inject the CSS script tags into the editor using JS. I was attempting to do something similar before I found the Custom CSS and JS plugin.

As far as I am aware though, the colour theme side of things would need to remain a separate extension. I could be wrong on that though, this theme is my first foray into VS Code extensions.

**Comment by jcklpe** [comment]
@robb0wen  Rad! Thank you. 

How did you convert your theme token changes in settings.json over to a separate theme extension? Even if I have to separate stuff out into two extensions that still a whole lot more portable and maintainable than what I'm currently doing.

**Comment by robb0wen** [comment]
It's a bit messy due to how VS code generates the CSS from its theme json. I used the editor's dev tools to see which classnames it was assigning to the code. These are the `.mtkX { ... }` classes you can see. Once I had adjusted my colours I took these classes to write the CSS. 

My original extension was trying to inject the CSS into the editor context, but I found that the 'Custom CSS and JS' plugin existed and was already doing this job.

**Comment by jcklpe** [comment]
@robb0wen btw, I recently found out how to deal with this more natively within vscode. 

You'll still need to do the code injection stuff to get the glow etc, but I found that I can, in addition to writing a theme extension, I can also get a lot of the customized styling I like to do covered by writing a textMate grammar. https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide

**Comment by jcklpe** [comment]
@robb0wen Hey Robb, 

Finally got my own custom multipart theme packaged up and on the marketplace store! Thought I'd let you know since you were a big inspiration for me to take this stuff outside of my personal settings and actually make into an extension. 

https://marketplace.visualstudio.com/items?itemName=jcklpe.enzo

In addition to the css injection stuff you do, I also have an additional layer using regex hilighting. Originally wrote syntax rules to actually install like a native language file but unfortunately that stuff is less powerful than just using a regex based highlighting extension. 

Eventually I want to hack off the bits from the hilighting regex and the css injection tools into my own extension so that I can have a fully integrated theme extension that covers both the default theme functionality and my own custom functionality. 

Since your theme also has a similar use of third party functionality I was thinking maybe we could collab on that project eh? 

Anyway just wanted to let you know and say thanks again for the inspiration!
