### ISSUE TITLE
Enable Neon Dreams doesn't seem to work?

### ISSUE THREAD

**Issue by lourain** [robb0wen/synthwave-vscode#247]
![image](https://user-images.githubusercontent.com/26606163/145323803-348ba7aa-d131-4925-9d5d-ad710355a4ff.png)

![image](https://user-images.githubusercontent.com/26606163/145322758-efbc69ad-367d-4f5b-a899-fcc31dbb92b0.png)

**After updating vscode today, it won't work.**

**Comment by barguti** [comment]
try to open your command palette and choose "Enable Neon Dreams" option.

**Comment by lourain** [comment]
it's my fault.  it's working normally after reinstall vscode
