### ISSUE TITLE
Let's make a plugin to Hyper.js too!

### ISSUE THREAD

**Issue by diogocezar** [robb0wen/synthwave-vscode#25]
What do you think? I'm love with this theme, we could develop one for hyper.js too.

Do you know?

https://hyper.is/

**Comment by diogocezar** [comment]
There is my try.

https://github.com/diogocezar/hyper-synthwave84

**Comment by robb0wen** [comment]
Nice! I've seen a few themes like this cropping up for other editors, so I will collate them and add them to the readme soon.
