### ISSUE TITLE
Not working well in VSCode January 2022 (version 1.64)

### ISSUE THREAD

**Issue by 0ussamaBernou** [robb0wen/synthwave-vscode#252]
need to be reapplied for the glow to function, even after activating it manually with ctrl+shift+p

**Comment by isosphere** [comment]
Following an update to 1.64 on **Windows**, the extension has no effect for me until I disable the extension, reload, re-enable the extension, and set the color scheme. 

If I restart the editor it has to be done again. The usual run as Administrator, enable Neon Dreams, restart process does not work. 

It looks like whatever change the extension makes is no longer persistent due to VS Code changes.

Here's the release notes for the update: https://code.visualstudio.com/updates/v1_64

None of the changes look relevant to me, though I haven't dug into the code of this extension to know how it works besides that it changes some core CSS files. 

**Rolling back to 1.63.2 resolves the issue, the extension certainly works as intended on that version.**

**Comment by jruizsulime** [comment]
I have the same issue, today my VSCode updated to `1.64` and Neon Glow disabled permanently even restarting, changing theme, or executing as Administrator the Vscode.exe

![imagen](https://user-images.githubusercontent.com/22749661/152562898-3564a744-9fcf-451b-a4e7-0e0bca153ec7.png)

Others theme as Fluoromachine are working the Neon glow, so I don't know if there is only a problem with the vscode update or something else..

**Comment by cheestudio** [comment]
Chiming in here, I get the same behavior as @isosphere

**Comment by novym** [comment]
It looks like whatever this extension does to load the custom CSS isn't working correctly.
For a temporary fix on VSCode Version: 1.64.0 (Tested on Mac)

1. Install `Custom CSS and JS Loader` and `Fix VSCode Checksums`
2. Add this to your `settings.json` and save
----
Mac
```json
"vscode_custom_css.imports": [
    "file:///Users/{YOUR_USER_NAME}/.vscode/extensions/robbowen.synthwave-vscode-0.1.10/synthwave84.css"
]
```

Windows
```json
"vscode_custom_css.imports": [
    "file:///C:/Users/{YOUR_USER_NAME}/.vscode/extensions/robbowen.synthwave-vscode-0.1.10/synthwave84.css"
]
```
----
3.  Run command `Reload Custom CSS and JS` and click Reload button that pops up, or manually Restart VSCode
4.  You will get the message about a corrupt installation: Run command `Fix Checksums: Apply` and restart VSCode again

Current VSCode running on Mac
```
Version: 1.64.0
Commit: 5554b12acf27056905806867f251c859323ff7e9
Date: 2022-02-03T04:20:17.224Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0
```
![Screen Shot 2022-02-04 at 1 50 33 PM](https://user-images.githubusercontent.com/4384604/152594097-1d0e9f8e-a5e0-498c-811e-c13db8bcf21b.png)

**Comment by isosphere** [comment]
> It looks like whatever this extension does to load the custom CSS isn't working correctly. For a temporary fix on VSCode Version: 1.64.0 (Tested on Mac)
> 
>     1. Install `Custom CSS and JS Loader` and `Fix VSCode Checksums`
> 
>     2. Add this to your `settings.json` and save
> 
> 
> Mac
> 
> ```json
> "vscode_custom_css.imports": [
>     "file:///Users/{YOUR_USER_NAME}/.vscode/extensions/robbowen.synthwave-vscode-0.1.10/synthwave84.css"
> ]
> ```
> 
> Windows
> 
> ```json
> "vscode_custom_css.imports": [
>     "file:///C:/Users/{YOUR_USER_NAME}/.vscode/extensions/robbowen.synthwave-vscode-0.1.10/synthwave84.css"
> ]
> ```
> 
>     3. Run command `Reload Custom CSS and JS` and click Reload button that pops up, or manually Restart VSCode
> 
>     4. You will get the message about a corrupt installation: Run command `Fix Checksums: Apply` and restart VSCode again
> 
> 
> Current VSCode running on Mac
> 
> ```
> Version: 1.64.0
> Commit: 5554b12acf27056905806867f251c859323ff7e9
> Date: 2022-02-03T04:20:17.224Z
> Electron: 13.5.2
> Chromium: 91.0.4472.164
> Node.js: 14.16.0
> V8: 9.1.269.39-electron.0
> OS: Darwin x64 20.6.0
> ```
> 
> ![Screen Shot 2022-02-04 at 1 50 33 PM](https://user-images.githubusercontent.com/4384604/152594097-1d0e9f8e-a5e0-498c-811e-c13db8bcf21b.png)

I can confirm that this solution works for me on Windows, with the caveat that the "Reload Custom CSS and JS" step must be run as Administrator. 

Additional caveat: I adjusted my glow value using `"synthwave84.brightness": 1`, but that setting is no longer in effect and now it looks kind of dull. 

![image](https://user-images.githubusercontent.com/163370/152606993-6b4ee473-ba0f-43c2-bf3f-f475af1d2627.png)

**Comment by novym** [comment]
> I can confirm that this solution works for me on Windows, with the caveat that the "Reload Custom CSS and JS" step must be run as Administrator.
> 
> Additional caveat: I adjusted my glow value using `"synthwave84.brightness": 1`, but that setting is no longer in effect and now it looks kind of dull.
> 
> ![image](https://user-images.githubusercontent.com/163370/152606993-6b4ee473-ba0f-43c2-bf3f-f475af1d2627.png)

I tried changing that setting, and it doesn't do anything for me either.
I am not able to find `synthwave84.brightness` anywhere in the source code for this extension. 

In the css file for the extension, I believe its the last 2 HEX color digits in the `text-shadow` property that changes the brightness of the glow effect. You could try modifying those.
For example change:
```css
text-shadow: 0 0 2px #001716, 0 0 3px #03edf975, 0 0 5px #03edf975, 0 0 8px #03edf975;
```
To:
```css
text-shadow: 0 0 2px #001716, 0 0 3px #03edf999, 0 0 5px #03edf999, 0 0 8px #03edf999;
```

You may have to re run the custom css loader command afterwards.

**Comment by RCristiano** [comment]
> It looks like whatever this extension does to load the custom CSS isn't working correctly. For a temporary fix on VSCode Version: 1.64.0 (Tested on Mac)
> 
>     1. Install `Custom CSS and JS Loader` and `Fix VSCode Checksums`
> 
>     2. Add this to your `settings.json` and save
> 
> 
> Mac
> 
> ```json
> "vscode_custom_css.imports": [
>     "file:///Users/{YOUR_USER_NAME}/.vscode/extensions/robbowen.synthwave-vscode-0.1.10/synthwave84.css"
> ]
> ```
> 
> Windows
> 
> ```json
> "vscode_custom_css.imports": [
>     "file:///C:/Users/{YOUR_USER_NAME}/.vscode/extensions/robbowen.synthwave-vscode-0.1.10/synthwave84.css"
> ]
> ```
> 
>     3. Run command `Reload Custom CSS and JS` and click Reload button that pops up, or manually Restart VSCode
> 
>     4. You will get the message about a corrupt installation: Run command `Fix Checksums: Apply` and restart VSCode again
> 
> 
> Current VSCode running on Mac
> 
> ```
> Version: 1.64.0
> Commit: 5554b12acf27056905806867f251c859323ff7e9
> Date: 2022-02-03T04:20:17.224Z
> Electron: 13.5.2
> Chromium: 91.0.4472.164
> Node.js: 14.16.0
> V8: 9.1.269.39-electron.0
> OS: Darwin x64 20.6.0
> ```
> 
> ![Screen Shot 2022-02-04 at 1 50 33 PM](https://user-images.githubusercontent.com/4384604/152594097-1d0e9f8e-a5e0-498c-811e-c13db8bcf21b.png)

It worked for me on linux Fedora 35

I need to run this before:
```bash
sudo chown -R (whoami) /usr/share/code
```
and change:
```json
"vscode_custom_css.imports": [
    "file:///home/{YOUR_USER_NAME}/.vscode/extensions/robbowen.synthwave-vscode-0.1.10/synthwave84.css"
]
```

**Comment by ireznik** [comment]
> Additional caveat: I adjusted my glow value using `"synthwave84.brightness": 1`, but that setting is no longer in effect and now it looks kind of dull.
> 
> ![image](https://user-images.githubusercontent.com/163370/152606993-6b4ee473-ba0f-43c2-bf3f-f475af1d2627.png)

It is the same for me with and without WSL usage on Windows 11 😢

**Comment by jruizsulime** [comment]
Thanks for your support, with your comments it's seems working again !!

**Comment by robb0wen** [comment]
It does seem like the code for enabling the glow has stopped working as of the latest version of VS code, so I will look to get it fixed as soon as possible. 

Just an FYI - this extension hasn't used the Custom CSS and JS plugin for a long time now, so enabling it as a workaround might cause compatibility issues once I have been able to fix the core theme.

**Comment by cheestudio** [comment]
Thanks for looking into this @robb0wen! I think people's desire to find a workaround is a testament to how much we love this theme! I know personally had been hunting for the perfect theme for **years**. Once I found this one, I was able to stop searching! 🤩 Thanks again for creating/supporting this amazing extension!

**Comment by RCristiano** [comment]
> It does seem like the code for enabling the glow has stopped working as of the latest version of VS code, so I will look to get it fixed as soon as possible.
> 
> Just an FYI - this extension hasn't used the Custom CSS and JS plugin for a long time now, so enabling it as a workaround might cause compatibility issues once I have been able to fix the core theme.

I enabled the "Custom CSS and JS" extension, followed @novym's [recommendations](https://github.com/robb0wen/synthwave-vscode/issues/252#issuecomment-1030304398), and then disabled it. It fixed it for me and I no longer had to reactivate the glow at every start.

**Comment by robb0wen** [comment]
I've just published a new version of the extension (v0.1.11) to the VS code marketplace. This should fix the issue so that the glow loads on bootup.

If you have used the Custom CSS and JS workaround, disable that in case this causes further issues.

1. Disable Neon Dreams and restart.
2. Update to the new version of the extension
3. Enable Neon Dreams and restart.
4. Optionally run the fix checksums plugin (if you have it installed) to get rid of the "unsupported" message

Big thanks to @isosphere for suggesting swapping to another theme caused the glow to appear. That was a big help in identifying the cause of the failure. Cheers!

**Comment by ireznik** [comment]
> I've just published a new version of the extension (v0.1.11) to the VS code marketplace. This should fix the issue so that the glow loads on bootup.
> 
> 
> 
> If you have used the Custom CSS and JS workaround, disable that in case this causes further issues.
> 
> 
> 
> 1. Disable Neon Dreams and restart.
> 
> 2. Update to the new version of the extension
> 
> 3. Enable Neon Dreams and restart.
> 
> 4. Optionally run the fix checksums plugin (if you have it installed) to get rid of the "unsupported" message
> 
> 
> 
> Big thanks to @isosphere for suggesting swapping to another theme caused the glow to appear. That was a big help in identifying the cause of the failure. Cheers!

You are awesome. Thank you for your fast response 🥳

**Comment by projectintel-anon** [comment]
Still having trouble getting the glow to appear on Arch (Garuda) Linux. Weirdly enough, the Custom CSS and JS loader extension doesn't appeat on the marketplace, and installing it via the command line doesn't seem to work either. Hmm.

**Comment by jruizsulime** [comment]
Hello! Just for confirm that with the update `v.0.1.11` everything is working fine as expected and we have the best theme runing again! <3 Thanks so much @robb0wen  !!!

**Comment by cheestudio** [comment]
I second @jruizsulime, it's working perfect again!

That was a terrifying 24 hours...

**Comment by robb0wen** [comment]
Glad to see this is working again.

@projectintel-anon the latest version of the theme doesn't need the Custom CSS and JS loader plugin to enable the glow. Have you got v0.1.11 of Synthwave '84 installed? did the glow work for you previously?

**Comment by projectintel-anon** [comment]
@robb0wen So after digging a little deeper, I found out that I could not get the glow to work on VS Code that was installed via Snap or "Code OSS" (default on pacman). The glow only works for me on the chaotic-aur version or if I build it directly from git.

Nonetheless I got it working!
