### ISSUE TITLE
Issue Enableing neon Dreams on Windows

### ISSUE THREAD

**Issue by xXDeathAbyssXx** [robb0wen/synthwave-vscode#253]
Using `Ctrl+Shift+P` then `Enable Neon Dreams` and restarting vsc doesn't set the neon color, it's still the same, thanks for reading.

![Code_ntLhRNiiC2](https://user-images.githubusercontent.com/97713025/152619737-78b868ac-c18d-4219-91be-fabc9e9ea041.png)

**Comment by Bonnary** [comment]
I had the same issues a couple of days it worked but now doesn't, I have been reinstalling it and `Enable Neon Dreams` a couple but still the same.

**Comment by Bonnary** [comment]
Just found a solution and it's worked for me
https://github.com/robb0wen/synthwave-vscode/issues/252#issuecomment-1030304398

**Comment by xXDeathAbyssXx** [comment]
yes! tysm now i fix it manually.
