### ISSUE TITLE
my imports and other code doesnt light up even with neon enabled

### ISSUE THREAD

**Issue by Arodlives** [robb0wen/synthwave-vscode#279]
<img width="1143" alt="neon" src="https://user-images.githubusercontent.com/46770499/202345684-d18e9c56-5948-4377-b238-695ef8125105.PNG">

**Comment by mpekarMPB** [comment]
Same issue, suddenly stopped working on 3 machines. Both Windows and Mac

**Comment by mpekarMPB** [comment]
Figured it out. It was a rogue extension JavaScript & TypeScript Nightly by Microsoft that was breaking the colours. https://stackoverflow.com/questions/74470708/vscode-syntax-highlighting-not-working-for-javascript-typescript

**Comment by Arodlives** [comment]
> Figured it out. It was a rogue extension JavaScript & TypeScript Nightly by Microsoft that was breaking the colours. https://stackoverflow.com/questions/74470708/vscode-syntax-highlighting-not-working-for-javascript-typescript

FIxed than you
