### ISSUE TITLE
[Question] any plan on releasing for VS2017?

### ISSUE THREAD

**Issue by BelleGueule** [robb0wen/synthwave-vscode#28]
i don't know much about theme creation so i don't know if it's possible without too much hassle,

**Comment by robb0wen** [comment]
I don't personally have plans to port it at the moment, but I'd welcome anyone who wanted to try. If VS2017 supports custom CSS in themes then there's no reason why it wouldn't also be possible

**Comment by beastlike** [comment]
somebody please do this. @robb0wen this theme is amazing!

**Comment by BelleGueule** [comment]
@beastlike  if by any chances you're a unity developer, VS Code works surprisingly well with unity all you need is two additional extensions

![image](https://user-images.githubusercontent.com/907190/57153028-38b51880-6da3-11e9-8899-b4bc05688b71.png)
