### ISSUE TITLE
Change modified file sidebar color to not connote errors

### ISSUE THREAD

**Issue by kadamwhite** [robb0wen/synthwave-vscode#3]
In other themes like Monokai, modified and untracked files without critical errors appear in recognizable-but-neutral colors like green and beige:
![image](https://user-images.githubusercontent.com/442115/56921495-ea96d100-6a93-11e9-8f0c-4d5e86ca8f32.png)

then this changes to brighter, error-associated colors like red or orange if there are syntax errors in the file:
![image](https://user-images.githubusercontent.com/442115/56921523-fbdfdd80-6a93-11e9-8e12-72198e235cd6.png)

In Synthwave (which is fantastic, by the way; thanks for releasing it!) the default color for Modified files is one that, to me, signals the presence of an error:
![image](https://user-images.githubusercontent.com/442115/56921555-0f8b4400-6a94-11e9-9239-124abf1d1368.png)
While this changes to a _stronger_ red when an error is present (![image](https://user-images.githubusercontent.com/442115/56921580-22057d80-6a94-11e9-9f27-470026c5afd8.png)) it has tripped me up a few times already to look at a modified file and think it contains errors when there are none.

I'd like to suggest that a different color be used to signal modified-but-not-errored files in the sidebar, to avoid this cognitive dissonance.

Thanks!

**Comment by robb0wen** [comment]
Good shout. I'll get this fixed
