### ISSUE TITLE
Error when trying to turn on the neon effects after last update - VS CODE

### ISSUE THREAD

**Issue by DavidZerox8** [robb0wen/synthwave-vscode#324]
![error](https://github.com/user-attachments/assets/f2e5beb7-9101-49c2-8e35-88a4edaf4ed0)

**Comment by skl** [comment]
+1 same on macOS:

<img width="255" alt="Screenshot 2024-10-07 at 19 02 41" src="https://github.com/user-attachments/assets/b362d685-fa6d-4489-b126-42e14058db20">

**Comment by muhammad-mobeen** [comment]
Same error on Windows. Was working fine when I restarted VScode for update and after restarting I tried to turn on neon but it shows the above dialog box.

**Comment by PangaeaUltima** [comment]
> +1 same on macOS:
> 
> <img alt="Screenshot 2024-10-07 at 19 02 41" width="255" src="https://private-user-images.githubusercontent.com/514343/374280250-b362d685-fa6d-4489-b126-42e14058db20.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzMzIwNDYsIm5iZiI6MTcyODMzMTc0NiwicGF0aCI6Ii81MTQzNDMvMzc0MjgwMjUwLWIzNjJkNjg1LWZhNmQtNDQ4OS1iMTI2LTQyZTE0MDU4ZGIyMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwN1QyMDA5MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NTJiNTIyOTJmM2M5MThmMjdiNjY5ZTE0NTJkZmQ4Y2FkMTRhNWI0N2MxOTQ2ZTI5ZjBkZTk2NGMxMjk4YzQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.0FB8n6awMZ0Zlocr37CfHdyCvEq_f3tpp25U_IM6jZo">

Same error for me on macOS :(

**Comment by jcbombardelli** [comment]
Unfortunately , I have the same problem

![image](https://github.com/user-attachments/assets/306a945f-1068-4af4-b12a-f79b58a2d9c4)

**Comment by jcbombardelli** [comment]
To solve the problem, just go to the extension.js file, and put this code, replacing lines 26 to 41

```javascript
const isWin = /^win/.test(process.platform);
      const appDir = `${path.dirname(vscode.env.appRoot)}/app/out`;
      const base = appDir + (isWin ? "\\vs\\code" : "/vs/code");
      const electronBase = isVSCodeBelowVersion("1.70.0")
        ? "electron-browser"
        : "electron-sandbox";
      const htmlFile =
        base +
        (isWin
          ? "\\" + electronBase + "\\workbench\\workbench.esm.html"
          : "/" + electronBase + "/workbench/workbench.esm.html");
      const templateFile =
        base +
        (isWin
          ? "\\" + electronBase + "\\workbench\\neondreams.js"
          : "/" + electronBase + "/workbench/neondreams.js");
```

**Comment by DavidZerox8** [comment]
Thanks @jcbombardelli, it's solved, i share my VS Code info for future references:

Version: 1.94.0 (user setup)
Commit: d78a74bcdfad14d5d3b1b782f87255d802b57511
Date: 2024-10-02T13:08:12.626Z
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22000

**Comment by muhammad-mobeen** [comment]
@jcbombardelli Thanks for the help, it definitely worked and required a restart of the extensions. 🚀

**Comment by jeFF0Falltrades** [comment]
Thank you @jcbombardelli - I know this Issue was closed, but are there plans then to pull these changes into the extension, or is it easier to wait for another update to Code?
