### ISSUE TITLE
error in neon dreams synthwave 84 

### ISSUE THREAD

**Issue by vcancode** [robb0wen/synthwave-vscode#325]
![image](https://github.com/user-attachments/assets/cce40af3-e10a-43ba-a45b-93796fb215a3)

**Comment by Manu254rce** [comment]
Hi

You can check out [this link](https://github.com/robb0wen/synthwave-vscode/issues/319#issuecomment-2396533289) hopefully you can find a solution to the problem

**Comment by vinayakkulkarni** [comment]
> ![image](https://private-user-images.githubusercontent.com/183459107/374794936-cce40af3-e10a-43ba-a45b-93796fb215a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MzAyMzgsIm5iZiI6MTcyODcyOTkzOCwicGF0aCI6Ii8xODM0NTkxMDcvMzc0Nzk0OTM2LWNjZTQwYWYzLWUxMGEtNDNiYS1hNDViLTkzNzk2ZmIyMTVhMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMlQxMDQ1MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MThiMzFiM2NkYmIwMjRlODVhN2Y2NGY4Yjk5OTNlOGVlNDJjMWIyNTgwOTdhYWU1Yzc0MGNmYTk0MTc5NGM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.yhq5-SBLYU34YeriGT1bJwB4MwGe3uHZIi4Mh1EqFlk)

temporary fix for v1.94 https://github.com/robb0wen/synthwave-vscode/issues/317#issuecomment-2351804426

fix for v1.95 - https://github.com/robb0wen/synthwave-vscode/pull/318/files

**Comment by robb0wen** [comment]
This issue should now be fixed in v0.1.16
