### ISSUE TITLE
After starting with the syntax Ctrl + Shift + P, I got this error. How should I handle it?

### ISSUE THREAD

**Issue by Iamtaitc** [robb0wen/synthwave-vscode#329]
![image](https://github.com/user-attachments/assets/22794ed0-ac1d-4424-8fc3-047db167c1f4)

**Comment by Chharlie1130** [comment]
as a mac user, also want to know why: the same issue. Last day i try all the ways i can find but still fail to load my glow effect.

**Comment by vinayakkulkarni** [comment]
temporary fix for v1.94 https://github.com/robb0wen/synthwave-vscode/issues/317#issuecomment-2351804426

fix for v1.95 - https://github.com/robb0wen/synthwave-vscode/pull/318/files

**Comment by UR-Hiro** [comment]
Can anyone teach me how to update the extension.js

**Comment by FrCornaire** [comment]
> Can anyone teach me how to update the extension.js

The file you want to update should be in your $USER/.vscode/extensions/robbowen.synthwave-...

**Comment by UR-Hiro** [comment]
> > Can anyone teach me how to update the extension.js
> 
> The file you want to update should be in your $USER/.vscode/extensions/robbowen.synthwave-.../src

Did it work for you? I feel like i'm doing it wrong. It didnt work for me.

**Comment by FrCornaire** [comment]
yeah it's work for me with @vinayakkulkarni  patch

![image](https://github.com/user-attachments/assets/6aaa6dc4-7491-4200-8303-49c830f459f2)

**Comment by UR-Hiro** [comment]
> > > > Can anyone teach me how to update the extension.js
> > > 
> > > 
> > > The file you want to update should be in your $USER/.vscode/extensions/robbowen.synthwave-.../src
> > 
> > 
> > Did it work for you? I feel like i'm doing it wrong. It didnt work for me.
> 
> yeah it's work for me with @vinayakkulkarni patch
> 
> ![image](https://private-user-images.githubusercontent.com/153903893/376239410-6aaa6dc4-7491-4200-8303-49c830f459f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5MDkzODQsIm5iZiI6MTcyODkwOTA4NCwicGF0aCI6Ii8xNTM5MDM4OTMvMzc2MjM5NDEwLTZhYWE2ZGM0LTc0OTEtNDIwMC04MzAzLTQ5YzgzMGY0NTlmMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNFQxMjMxMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMzM5YjZhZGI2MmRiZTk3OTlhMGFlZDcwNjIzZDZjMGI0ZTE3ZTlhYTZiYTM4OWJiOTczOWNkMjJjNTRhYTYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.rIRvNnksUolyyXQyzGTzAYm_RNeKGXju6ypioT54sek)

THANKSSS!!!! IT'S WORKING NOW. MY BRAIN CAN FINALLY FUNCITON NOW.

**Comment by robb0wen** [comment]
This issue should now be fixed in v0.1.16
