### ISSUE TITLE
macOS Sequoia 15.0.1  Vscode升级至1.94.2后，SynthWave '84启用不了

### ISSUE THREAD

**Issue by ciycy** [robb0wen/synthwave-vscode#330]
macOS Sequoia 15.0.1  Vscode升级至1.94.2后，SynthWave '84启用不了，如下图。

<img width="260" alt="image" src="https://github.com/user-attachments/assets/c43870ff-a399-42b7-b350-f7cf149b8210">

**Comment by vinayakkulkarni** [comment]
Workaround – https://github.com/robb0wen/synthwave-vscode/issues/317#issuecomment-2351804426
PR (w/ 1.95 fix) – https://github.com/robb0wen/synthwave-vscode/pull/318

**Comment by robb0wen** [comment]
This issue should now be fixed in v0.1.16
