### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by onerandomcoder2** [robb0wen/synthwave-vscode#331]
cannot read properties of undefined (reading filename)

**Comment by vinayakkulkarni** [comment]
Workaround – https://github.com/robb0wen/synthwave-vscode/issues/317#issuecomment-2351804426
PR (w/ 1.95 fix) – https://github.com/robb0wen/synthwave-vscode/pull/318

**Comment by onerandomcoder2** [comment]
i updated my extension with that and it still had the same error

**Comment by robb0wen** [comment]
This issue should now be fixed in v0.1.16
