### ISSUE TITLE
no funciona en modo administrador 

### ISSUE THREAD

**Issue by kevinRT19** [robb0wen/synthwave-vscode#332]
![Captura de pantalla 2024-10-29 180838](https://github.com/user-attachments/assets/a4994ed7-9cbe-466f-a49f-b8261f22f675)
lo ejecuto en modo administrador pero aun asi me sigue saliendo el error alguien sabe la solucion dejo de funcionar en la version de visual estudio 1.95 en windows

**Comment by keyork** [comment]
I'm having the same issue and the problem is coming again...

**Comment by robb0wen** [comment]
I've just published a fix in v0.1.17, which should now be available on the VS code marketplace.
