### ISSUE TITLE
Neon Dreams was unable to modify the core VS code files needed to launch the extension

### ISSUE THREAD

**Issue by Lucas-fost** [robb0wen/synthwave-vscode#335]
Hitting this error when trying to enable Neon Dreams on MacOS after VSCode updated to 1.95.0
```
Neon Dreams was unable to modify the core VS code files needed to launch the extension. 
You may need to run VS code with admin privileges in order to enable Neon Dreams.
```
Which wouldn't be an issue, except there's no way to run an app with admin privileges on MacOS, so kinda stuck. Does anyone know of a way to resolve it?

**Comment by robb0wen** [comment]
I've just published a fix in v0.1.17, which should now be available on the VS code marketplace.
