### ISSUE TITLE
only glow part of it

### ISSUE THREAD

**Issue by iceman201** [robb0wen/synthwave-vscode#39]
![image](https://user-images.githubusercontent.com/5027957/57057671-b8d57280-6cfe-11e9-8aad-93e050469c42.png)

**Comment by lesleyhogg** [comment]
My JavaScript files also only glow for comments and numbers. (CSS looks great, though.)

![Screen Shot 2019-05-02 at 1 44 37 PM](https://user-images.githubusercontent.com/32503346/57095310-8b79cc00-6ce0-11e9-94c5-e1b903bab558.png)

**Comment by federicobarera** [comment]
sample problem, anyone figured it out yet?

**Comment by iceman201** [comment]
Thank you @federicobarera  problem solved

**Comment by robb0wen** [comment]
> You can actually go in Chose Theme in VsCode and search for SynthWave84 and install it and it does the trick. I don't understand why the readme goes with manual install

There's a two part install. The theme should be downloaded and installed from vs marketplace, as per any other theme. The manual install instructions are for the CSS. Sorry if this wasn't clear from the Readme. I'll take a look at updating it.

**Comment by lesleyhogg** [comment]
Yup, for other people reading this later, you go to Preferences > Color Theme, search for Synthwave '84, then install that.

**Comment by federicobarera** [comment]
@robb0wen thanks for updating the readme, much clearer now! And great work for the theme! It's awesome!
