### ISSUE TITLE
scroll bar invisible

### ISSUE THREAD

**Issue by Joyrocky** [robb0wen/synthwave-vscode#40]
I can't see the scroll bar scrolling while scrolling the mouse wheel.So please give a color contrast to the scroll bar against the background so that we can tell it and then left click it to control it move tinily.Thank you!

**Comment by robb0wen** [comment]
This has been addressed in #26 and pushed in v0.0.7

**Comment by JeroMiya** [comment]
@robb0wen Scrollbar is still quite faint in 0.0.7. Can we make it brighter?
