### ISSUE TITLE
No effect in vscode Version: 1.33.1 OS: Linux x64 4.15.0-48-generic

### ISSUE THREAD

**Issue by AELe** [robb0wen/synthwave-vscode#41]

**Comment by flyerooo** [comment]
you can follow this document [vscode-custom-css](https://github.com/be5invis/vscode-custom-css)

**Comment by AELe** [comment]
Thank you for your help @flyerooo .I had tried to modified the ownership of code but it kept the not glow.

**Comment by nmilford** [comment]
Exact same issue here.

Same version, same version.  sudo chown -R me /usr/share/code

No glow.  I wonder if maybe the linux build of code has some additional security garbage preventing the include of the CSS...

**Comment by pulberg** [comment]
check perms on the .css file itself, and/or move to a diff dir.

**Comment by nmilford** [comment]
Yup, moving it to /tmp worked

**Comment by AELe** [comment]
Thank you very much@nmilford and @pulberg .I changed the file .css to other folder(eg./home/user/) and it`s worked.
