### ISSUE TITLE
Theme for other softwares ?

### ISSUE THREAD

**Issue by Epistol** [robb0wen/synthwave-vscode#42]
Hey there, I don't use VSCode but I already love this theme, do you plan to export it to other software for dev, like PHPStorm or SublimeText for example ?

Congrats again,
Epistol

**Comment by clawfire** [comment]
I need that for Atom

**Comment by robb0wen** [comment]
I personally don't have plans to port this to other editors at the current time. That said, it's open source and I welcome it if anyone else would like to take on the task!

**Comment by eltonnuness** [comment]
I need that for IDEA
