### ISSUE TITLE
Glow theme

### ISSUE THREAD

**Issue by csutorasr** [robb0wen/synthwave-vscode#44]
Could you add the glowing theme as a new one? This way no tweaks would be needed. (Those are not working for me anyway.)

**Comment by robb0wen** [comment]
I'm not sure I understand what you mean, sorry. Would it be possible to add more details of your idea please?

**Comment by ranolfi** [comment]
@robb0wen <sub>(first of all thanks for the extension)</sub> I think he means you package two themes, one of which makes the glow effects work without the end user having to perform any manual tweak.

Look for example how the OneDark Pro theme package has multiple options:
![image](https://user-images.githubusercontent.com/8507649/57144952-9859f680-6d98-11e9-91ba-ad3476df3a85.png)

If possible there should be another SynthWave '84 theme to switch glow on/off.

**Comment by robb0wen** [comment]
Ah I see. Thanks.
In which case, unfortunately that isn't possible at the moment. There's no simple means of adding the glowing text-effect to a theme without including the workaround for custom CSS files. 

I wish it weren't the case, but until (or rather, if) VS Code gets native support for custom CSS files I don't think this will be possible.

**Comment by csutorasr** [comment]
Sorry for being unclear. I have never created a theme. I just know this must be possible.

It is bad to hear this is not possible. I did not found any vscode issue on it. Maybe we can start it.

**Comment by shrgabor** [comment]
Hey @robb0wen,
I like this theme really much, but I have bad feelings about the custom CSS, and JS loader plugin.
Can you please elaborate on why is it not possible? I'm familiar with web technologies but a complete newbie to VS Code extensions.
Why is it have to be a custom CSS? Why can't you include it in the extension? 
I'm really looking forward to your answer. :)
