### ISSUE TITLE
Is this theme support python?

### ISSUE THREAD

**Issue by RyuAsuka** [robb0wen/synthwave-vscode#46]
It seems not supporting Python. I have installed this theme and correctly configured it via settings.json. But my Python codes are still keeping its original style.

**Comment by skourismanolis** [comment]
What do you mean when you say 'original style'? Syntax highlighting works as it should for me, does it look like this to you too?
![image](https://user-images.githubusercontent.com/44413349/57135705-090e0c80-6db3-11e9-8e5b-ed3055650360.png)

**Comment by RyuAsuka** [comment]
Oh sorry. I have no problems now. I forgot enabling the custom CSS.

**Comment by nihaalnz** [comment]
@skourismanolis  The colors seem different on my version of code, and keeps changing no matter what, even if I change them in the json file.

**Comment by skourismanolis** [comment]
@nihaalnz I think syntax highlighting is provided by vscode's built-in language service and it has nothing to do with this theme. Do you experience the same issue using other themes?

**Comment by nihaalnz** [comment]
@skourismanolis Noo, material theme is just perfect !

**Comment by skourismanolis** [comment]
@nihaalnz interesting, I guess you should go ahead and open an new issue, I'd recommend you add as much info as possible incl what system you're on, python version and some screenshots.
