### ISSUE TITLE
Not working on VSCode 1.30.2 (Linux)

### ISSUE THREAD

**Issue by thiagoiferreira** [robb0wen/synthwave-vscode#47]
So, I've been trying to configure the theme on the settings.json file but it doesn't seem to be recognizing the custom theme, these are my current settings:
```
{
    "vscode_custom_css.imports": ["file:///home/kyo/Downloads/synthwave-vscode-0.0.6/synthwave84.css"],
    "vscode_custom_css.policy": true,
    "gitlens.advanced.messages": {
    "suppressCommitHasNoPreviousCommitWarning": false,
    "suppressCommitNotFoundWarning": false,
    "suppressFileNotUnderSourceControlWarning": false,
    "suppressGitVersionWarning": false,
    "suppressLineUncommittedWarning": false,
    "suppressNoRepositoryWarning": false,
    "suppressResultsExplorerNotice": false,
    "suppressShowKeyBindingsNotice": true
},
"gitlens.historyExplorer.enabled": true,
"workbench.iconTheme": "material-icon-theme",
"window.zoomLevel": -1,
}
```

I've tried removing the gitlens configuration and that doesn't seem to be interfering with the general settings.
I've done all the steps involving the custom CSS and JS extension, including the part which I had to give permission to the application for it to modify itself.
I can't seem to find any solutions. Any suggestions on what I should do? Am I doing something wrong or is the app just incompatible with this version of vscode?

**Comment by Dogzik** [comment]
Same problem with ubuntu19.04 with code 1.33.1
Color scheme applies, but without any glow
![image](https://user-images.githubusercontent.com/26696217/57400443-2f311380-71dc-11e9-8723-a86f8cb792ad.png)

**Comment by robb0wen** [comment]
The CSS file itself might need permissions adjusting. I can see from your settings that it's in downloads and I know that another user found that their downloads path was blocking access to the CSS file. I'd look there to start. Alternatively, try moving the CSS file to a different path altogether.

Have you installed and enabled the base synthwave theme from VS marketplace?

**Comment by thiagoiferreira** [comment]
I downloaded the themes extension from the marketplace, at the time I had opened the issue I think it wasn't there, very nice, thank you.
