### ISSUE TITLE
Glow not working on macOS - VSCode Version 1.33.1 (1.33.1)

### ISSUE THREAD

**Issue by markmcgookin** [robb0wen/synthwave-vscode#49]
I've installed the plugin, I've installed the js/css plugin, I've enabled custom css/js, I've added the css file, I've updated settings.json, I've given 'everyone' read/write of the css file. I am using the dotnet core c# plugin/editor and not seeing any glow on .cs or .json files.

`{
    "git.enableSmartCommit": true,
    "git.autofetch": true,
    "git.confirmSync": false,
    "window.zoomLevel": 0,
    "workbench.iconTheme": "city-lights-icons-vsc-light",
    "editor.fontFamily": "Inconsolata, Menlo, Monaco, 'Courier New', monospace",
    "editor.fontSize": 15,
    "terminal.integrated.fontSize": 15,
    "workbench.colorTheme": "SynthWave '84",
    "vscode_custom_css.imports": [
        "file:///Users/markmcgookin/Source/synthwave84.css"
    ]
}`

**Comment by robb0wen** [comment]
Sorry to hear that. Do you see glow on any other file types, JS or HTML for example? 

The glow on JSON files in particular is deliberately very minimal. My reasoning is that JSON tends to contain large amounts of text or html data, so it all glowing would be a bit much. I'm not personally a C# user so it might not yet be well optimised for that language.

**Comment by jinfagang** [comment]
@robb0wen  I can confirm that vscode 1.33.1 does not work with glow effect.

![image](https://user-images.githubusercontent.com/21303438/57305537-d5651680-7113-11e9-9be3-23545fa7abb4.png)

I have enabled custom css and js loader

**Comment by idrisadetunmbi** [comment]
Same here, glow was previously working until I opened VSCode today (updated to version 1.33.1 and the plugin to v0.0.7) and no glow again 😢

**Comment by kokarn** [comment]
I can deny this, it works as intended

![Screenshot 2019-05-07 at 16 41 02](https://user-images.githubusercontent.com/1373940/57308622-fe22e700-70e6-11e9-8ed3-b2e13c008113.png)

**Comment by kokarn** [comment]
Also
>Every time you update VS code, you will need to repeat this step to re-enable custom CSS and JS. Similarly, when the theme updates, you will need to copy the updated css to your chosen location.

https://github.com/robb0wen/synthwave-vscode#updates

**Comment by jinfagang** [comment]
@kokarn  obviously we are not in the same OS. maybe macos work. However, I just upgrade vscode long time ago and then install synthwave as well as open glow.

It can be confirmed that not work on Ubuntu 18.04 at least.

**Comment by kokarn** [comment]
Absolutely, but this issue has "macOS" in the title so figured might as well post :)

**Comment by henriquelbsouza** [comment]
I finally made it work on ubuntu, I had to do this: 
>Reload Custom CSS and JS

Even after the enable, changing permission on the vscode and files, and stuff...
Then it worked :D

**Comment by vuchan** [comment]
@henriquelbsouza  yes, when i executed this command `Reload Custom CSS and JS` it works well.

@robb0wen i think you should put this command in the README.md to let others people has less confusing.

**Comment by CHAO-LI-CHEN-STEVEN** [comment]
I have version 1.38
mine does not glow now

**Comment by sylviacastroco** [comment]
Thanks @henriquelbsouza , just as @vuchan has said, after executing `Reload Custom CSS and JS` it worked!!!

**Comment by markmcgookin** [comment]
I think this is fixed now and this has been open a year so I'll kill it

**Comment by jonjieviduya** [comment]
> Also
> 
> > Every time you update VS code, you will need to repeat this step to re-enable custom CSS and JS. Similarly, when the theme updates, you will need to copy the updated css to your chosen location.
> 
> https://github.com/robb0wen/synthwave-vscode#updates

@kokarn Thanks for sharing the link. That fix works for me :)
