### ISSUE TITLE
Glow not working on Ubunutu 19.04 VSCODE V1.33.1

### ISSUE THREAD

**Issue by weezyjr** [robb0wen/synthwave-vscode#51]
![Screenshot from 2019-05-03 13-39-38](https://user-images.githubusercontent.com/32999450/57135619-5043cf80-6daa-11e9-9ceb-398c03d0dc0e.png)

I've added the right css file with correct path to the settings, and enabled the custom css, but still there is no glow :(

**Comment by nmilford** [comment]
I moved the CSS out of my home directory to /tmp and it started working.

**Comment by robb0wen** [comment]
Some users have been seeing permissions issues on the CSS file itself. I haven't tried the theme on Ubuntu, but it could be that the home directory is blocking access to the CSS.

**Comment by pulberg** [comment]
@robb0wen For me, on Mac OS 10.14.4, it was both the perms on the .css file AND the location.  I decided it was just easier to reference the unmodified file in the default vscode extensions path - 

`/Users/<username>/.vscode/extensions/robbowen.synthwave-vscode-0.0.7/synthwave84.css`

**Comment by robb0wen** [comment]
@pulberg That's good to know, thanks.

Originally I wanted to reference the extension install path in the readme but because the path updates with the version, I decided it might confuse things even more. I long for VS Code to allow custom CSS natively.

**Comment by weezyjr** [comment]
I have moved the css to more open folders and ensured that the file has the read and write permissions, but still i have no glow :(

Is there any other ways to load the css file other than "custom css and js loader" extension ?

**Comment by pulberg** [comment]
I'll try it on my Ubuntu laptop and report back...

**Comment by Walwode** [comment]
same for me, on windows 10.

{
    "workbench.colorTheme": "SynthWave '84",
    "vscode_custom_css.imports": [
        "file:///C:/temp/synthwave84.css"
    ],
    "vscode_custom_css.policy": true
}

Shift+Click on file shows the file exists. CSS Extension is enabled. Any think else to look at?
VS 1.33.1

**Comment by pulberg** [comment]
I have tried everything, I cannot get it to work in vscode 1.33.1 on Ubuntu 19.04

**Comment by sizovmm** [comment]
@pulberg I've managed fix it in Kubuntu 18.04 by changing ownership of vscode package (I use VSCode from snap repo). As [customcss readme says](https://marketplace.visualstudio.com/items?itemName=be5invis.vscode-custom-css), you need to claim ownership on Code's installation directory, by running this command:
sudo chown -R $(whoami) <Path to Code>, in my case it was /usr/share/code
After that I enabled and reloaded custom css with ctrl+shift+p

**Comment by weezyjr** [comment]
Thanks @sizovmm you are right.
now it works :)

**Comment by pulberg** [comment]
@sizovmm I had already done the "chown" cmd with no luck.  What is interesting though, is that you say you installed vscode from the snap repo, which is what I did, but my path is diff - 

`phillip@phillip-ThinkPad-T450s:/usr/share$ cd code`
`bash: cd: code: No such file or directory` 

Here is what I found - 

`phillip@phillip-ThinkPad-T450s:/usr/share$ which code`
`/snap/bin/code`

`code -> /usr/bin/snap`

I'm going to remove the snap installed vscode and install from the .deb pkg.

**Comment by Hganavak** [comment]
Finally got it working for me on Ubuntu 18.10.

Interestingly `which code` gives me:

```
[sam@cer-laptop ~] λ which code
/usr/bin/code
```

But `ps -aux | grep code` gave me:
```
[sam@cer-laptop ~] λ ps -aux | grep code
sam      29711  5.5  0.8 1469172 138336 ?      Ssl  10:18   0:31 /usr/share/code/code
```

Sure enough repeating the install process after running `chown -R $(whoami) /usr/share/code` got it working for me :man_shrugging:

**Comment by henriquelbsouza** [comment]
I finally made it work on ubuntu, I had to do this:

    Reload Custom CSS and JS

Even after the enable, changing permission on the vscode and files, and stuff...
Then it worked :D

**Comment by jqweryjson** [comment]
"vscode_custom_css.imports": ["file:///usr/share/code/synthwave84.css"],
Then:
sudo chown -R $(whoami) /usr/share/code
 And it working

**Comment by CHAO-LI-CHEN-STEVEN** [comment]
<img width="880" alt="Screen Shot 2019-11-20 at 12 20 21 PM" src="https://user-images.githubusercontent.com/55163921/69274890-2dcfa300-0b90-11ea-8310-d5e2a5df0599.png">

I have version 1.38 and It does not glow anymore

**Comment by jqweryjson** [comment]
> <img alt="Screen Shot 2019-11-20 at 12 20 21 PM" width="880" src="https://user-images.githubusercontent.com/55163921/69274890-2dcfa300-0b90-11ea-8310-d5e2a5df0599.png">
> 
> I have version 1.38 and It does not glow anymore

Try to ctrl+p then type Reload Custom CSS and JS and reload editor. Worked for me

**Comment by CHAO-LI-CHEN-STEVEN** [comment]
Thank you..,.!
