### ISSUE TITLE
Consider higher-visibility active tab styles

### ISSUE THREAD

**Issue by kadamwhite** [robb0wen/synthwave-vscode#52]
![image](https://user-images.githubusercontent.com/442115/57136446-e4963e00-6d7a-11e9-8d99-53bb2aa2caf8.png)

The styles for a selected editor tab and an unselected editor tab are very close, and the one-pixel border on the bottom of the active tab and slightly lighter font color are too subtle (for me, at least) to quickly identify the active tab. I'm not sure what would be best here, but a change of background color (either to emphasize the active tab, or de-emphasize the inactive ones), a thicker bottom border, or even brighter text might each independently make it easier for the active tab to catch the eye.

**Comment by kadamwhite** [comment]
I'm wary of the risk of referring too often to Monokai — no theme is perfect! — but it provides an example of the background-intensity option, providing greater contrast between active and inactive tab backgrounds
![image](https://user-images.githubusercontent.com/442115/57136866-1cea4c00-6d7c-11e9-9763-d52fda028e78.png)

**Comment by hadriengerard** [comment]
@kadamwhite this is what I'm using in my user/settings.json to slightly improve the contrast
`"workbench.colorCustomizations": {
        "tab.border": "#281d35",
        "tab.inactiveBackground": "#241b2f",
        "tab.activeModifiedBorder": "#880088"
},
"workbench.editor.highlightModifiedTabs": true,`

It uses the same color as the sidebar background for inactive tabs and highlight modified ones.

**Comment by DimitriLambrou** [comment]
@kadamwhite Yeah some of the sections in the CSS is easy to change, I also found that the selected tab was hard to notice so this is what I changed

`/* Active tab neon */
.monaco-workbench .part.editor>.content .editor-group-container>.title .tabs-container>.tab.sizing-fit.active {
  box-shadow: inset 0 -5px 25px #03edf9; /*#fc28a825*/
  position: relative;
}

/* Active tab stripe */
.monaco-workbench .part.editor>.content .editor-group-container>.title .tabs-container>.tab.sizing-fit.active::after {
  content: '';
  position: absolute;
  bottom: -1px;
  left: 0;
  right: 0;
  height: 4px;
  background: linear-gradient(to right, #fc28a8, #fff951) !important;/* #fc28a8, #03edf9 */
  opacity: 1;
}`
(line 52 - 68 if youve not edited the file yet)
![Capture](https://user-images.githubusercontent.com/43768025/57273413-0e34c980-70db-11e9-975b-89ad7963b8c4.PNG)

You may change whatever you want but I find the neon blue to be very nice. You can even change the line at the bottom to only be neon pink or yellow.

**Comment by kadamwhite** [comment]
@hadriengerard Those user settings styles look great! Thanks for the workaround!
