### ISSUE TITLE
Add support for power mode

### ISSUE THREAD

**Issue by indie-rok** [robb0wen/synthwave-vscode#53]
I managed to manually add the [power mode](https://github.com/hoovercj/vscode-power-mode) with the theme.

It looks like this:

https://streamable.com/9lyy9

It would be cool to install it as a dependency of the theme or if it not possible, Maybe adding some bonus to the README with the correct additional instructions to set it up. (Custom settings.json for highlight color, etc)

I could send PR, but I would like to know if the dependency path is viable or we should stick only with the README update, or maybe nothing at all

@robb0wen

**Comment by robb0wen** [comment]
I'm a huge fan of power-mode, it's hilarious! 
That said, I'd rather not link it as any dependency of this theme. The neon glow is already something of a novelty and I don't want to push SynthWave '84 further into that territory.
