### ISSUE TITLE
Idea: Powershell Automated Install

### ISSUE THREAD

**Issue by iamkilo** [robb0wen/synthwave-vscode#55]
Hi, I wasn't sure the best place to share this, but I wrote something in Powershell that does most of the hard work for people for the glow part.

https://gist.github.com/iamkilo/afbbadc92b504deba093ba96174452cd

Just have to reload or enable the plugin when it's done. Does not require admin rights.

**Comment by Roma1n4** [comment]
@iamkilo you should make a pull request from it maybe they will consider using it

**Comment by robb0wen** [comment]
Closing legacy tickets. This feature was introduced in a later version :)
