### ISSUE TITLE
iTerm theme

### ISSUE THREAD

**Issue by d4rkr00t** [robb0wen/synthwave-vscode#66]
Thanks! It's a very nice theme! I've quickly put up an iterm theme, if anybody is interested:
 
<img width="980" alt="Screen Shot 2019-05-06 at 5 14 55 PM" src="https://user-images.githubusercontent.com/200119/57211957-73c67e80-7025-11e9-9b41-3f0078a92077.png">

Github wouldn't let me upload `*.itermcolors`, just rename this file to `synthwave84.itermcolors` and import in iterm :)

Iterm Theme: [synthwave84.txt](https://github.com/robb0wen/synthwave-vscode/files/3146900/synthwave84.txt)

**Comment by neon-sombrero** [comment]
This is sick, thanks for sharing. 

How did you colour the file size, user, date etc. of your `ls` / `la`? Using this theme I only have differently coloured files (dir/file/script etc) and using `ls -lG` doesn't change them.

**Comment by d4rkr00t** [comment]
It's `exa` not `ls` -> https://github.com/ogham/exa

**Comment by Argon-** [comment]
`LS_COLORS` controls `ls` colors.

**Comment by robb0wen** [comment]
Sweet! I'm going to add a section to the Readme linking to ports, so I'll make sure this is on it

**Comment by ajmora7** [comment]
Do you have the color values? Something similar to [this](https://github.com/altercation/solarized/tree/master/iterm2-colors-solarized#the-values)? Trying to customize my bash prompt to take advantage of the same scheme

**Comment by faviobecker** [comment]
Love this! Now we just need the glow effect, and it'd be perfect :D
