### ISSUE TITLE
How to set the background color to black instead of purple

### ISSUE THREAD

**Issue by TobiasTao** [robb0wen/synthwave-vscode#68]
Can I set the background color to black instead of purple?

**Comment by hadriengerard** [comment]
You just need to add this entry in your `settings.json`
```json
"workbench.colorCustomizations": {
    "[SynthWave '84]": {
        "editor.background": "#000"
    }
}
```
You may also have to set some values like these ones for more consistency: `tab.inactiveBackground`, `activityBar.background`,  `sidebar.background`, `statusBar.background`,             `titleBar.activeBackground` and `editorGroupHeader.tabsBackground`

**Comment by FatDong1** [comment]
`sidebar.background` is not allowed

**Comment by sammykumar** [comment]
@FatDong1 what do you mean it's not allowed?

P.S. I've added the following lines to ```settings.json``` make my editor black instead of purple. Still working on the main editor screen.

`
{  "workbench.colorCustomizations": {
        "[SynthWave '84]": {
            "editor.background": "#000",
            "sideBar.background": "#111111",
            "activityBar.background": "#212121",
        }
    }
}`

**Comment by FatDong1** [comment]
@sammykumar Thank you. It works.

**Comment by darvid** [comment]
this doesn't seem to work anymore after enabling neon dreams

**Comment by esurnema** [comment]
Doesn't seem to work for me either, looks like something in "Enable Neon Dreams" that covers the regular editor background

**Comment by UnbrokenLogic** [comment]
If you installed the themes extension using "Custom CSS and JS," you must add your themes file location to your settings.json ( To open settings.json in VS Code: press Ctrl + Shift + P and type Preferences: Open User Settings (JSON) ).

First, check the default location. The **default location** is found in your **VS Code extension folder**(for example: C:\Users\[your user_name]\.vscode\extensions\fernaandojr.synthwave-remix-min-darker-2.0.0\themes\synthwave84.css). It's located here, but I couldn't find it in that folder, so I downloaded "synthwave84.css" from the GitHub page. Once you find the CSS file, you add it to your setting.json 
If you haven't found it yet, you can access it using the following link: [https://gist.github.com/vaaski/f4450c3aabf1ebcbfc9cebba3a37966f](url)   **OR**  [synthwave84.css](https://github.com/user-attachments/files/29692249/synthwave84.css)

```
"vscode_custom_css.imports": [
    "file:///C:/Users/[your user_name]/Documents/custom.css",
    "file:///C:/Users/[your user_name]/Documents/synthwave84.css"
    "file:///C:/Users/[your user_name]/.vscode/extensions/fernaandojr.synthwave-remix-min-darker-2.0.0/themes/synthwave84.css"
],
```
After you add the code, press Ctrl + Shift + P again, search for "Enable Custom CSS and JS," and click Enter!


**_### About the sidebar color change_** : 
It worked for me when I edited the actual CSS extension file located in my folder. In my case, I had the "synthwave84.css" file in my Documents folder. I edited this CSS file, and it resolved my issue. I installed it using the "Custom CSS and JS" extension, so I accessed the CSS file and made the necessary changes : 
(Scroll to the absolute bottom of this synthwave84.css(it may be another theme, like the theme you choose) file and add the following code: )

```
/* Force line number margin to match editor background */
.monaco-editor .margin,
.monaco-editor .margin-view-overlays {
    background-color: #141414 !important;
}
```
**This solution worked perfectly for me**. If you want to edit additional settings, you can do so in your settings.json file.  If you want, you can use :
```
"workbench.colorCustomizations": {
    "[SynthWave '84]": {
        "editor.background": "#000",
        "editorGutter.background": "#000"
    },
    "[Dark SynthWave '84]": {
        "editor.background": "#000",
        "editorGutter.background": "#000"
    },
    "[SynthWave 84' Remix Min Darker (by FernaandoJr)]": {
        "editorGutter.background": "#000",

        // Main window
        "editor.background": "#0c0c0c",

        // Activity Bar (left icons)
        "activityBar.background": "#181818",
        "activityBar.foreground": "#d4d4d4",
        "activityBar.inactiveForeground": "#858585",
        "activityBar.border": "#181818",

        // Sidebar (Extensions, Explorer...)
        "sideBar.background": "#131212",
        "sideBar.foreground": "#e0e0e0",
        "sideBar.border": "#252526",
        "descriptionForeground": "#aaaaaa",

        // Search bar at the top
        "input.background": "#3c3c3c",
        "input.foreground": "#cccccc",
        "input.border": "#3c3c3c",

        // "INSTALLED" / "RECOMMENDED"
        "sideBarSectionHeader.background": "#252526",
        "sideBarSectionHeader.foreground": "#cccccc",
        "sideBarSectionHeader.border": "#252526",

        // Top of sidebar ("Extensions")
        "sideBarTitle.foreground": "#cccccc",

        // Editor tabs
        "editorGroupHeader.tabsBackground": "#1e1e1e",
        "editorGroupHeader.noTabsBackground": "#1e1e1e",

        "tab.activeBackground": "#1e1e1e",
        "tab.activeForeground": "#ffffff",

        "tab.inactiveBackground": "#252526",
        "tab.inactiveForeground": "#969696",

        "tab.border": "#252526",

        // Title bar
        "titleBar.activeBackground": "#1e1e1e",
        "titleBar.inactiveBackground": "#1e1e1e",

        // Panel (Terminal, Problems)
        "panel.background": "#1e1e1e",
        "panel.border": "#252526",

        // Changes the text link color to the default VS Code blue
        "textLink.foreground": "#3794ff",
        "textLink.activeForeground": "#3794ff",

        // Changes the button background and text to default blue
        "button.background": "#007acc",
        "button.foreground": "#ffffff",
        "button.hoverBackground": "#0062a3"
    },
    "[New Dark Synthwave 84']": {
        "editor.background": "#000",
        "editorGutter.background": "#000",
        "sideBar.background": "#111111", 
        "activityBar.background": "#212121"
    },
}
```
**_NOTE_**: You can customize the theme you're using by adding your own code, just like I did. For example, I am using the theme "[SynthWave 84' Remix Min Darker (by FernaandoJr)]." As a result, I have written a lot of code for that theme. You can insert the code above into any theme you choose.
