### ISSUE TITLE
Make it work with vue files (vetur extension)

### ISSUE THREAD

**Issue by mika76** [robb0wen/synthwave-vscode#7]
This is great! but it does not seem to work with vue files. Any way to enable that?
https://marketplace.visualstudio.com/items?itemName=octref.vetur

**Comment by lholznagel** [comment]
I just tried it and it seems to work just fine.
I am using vetur and opened a .vue file containing template, script and style tags. It works with and without glow.

**Comment by decentraliser** [comment]
same for me!

**Comment by mika76** [comment]
Yeah my whole vscode got corrupted when I installed this - probably the css extension - so it's possible it all works fine. Anyway I removed everything and now have a nice clean install so don't want to try again 😄

**Comment by decentraliser** [comment]
Actually my vs code says it might be corrupted at each start too, but it works fine... I didn't dig into it yet

**Comment by mika76** [comment]
Yeah it was that but also that my vue files stopped with any syntax coloring...
