### ISSUE TITLE
双击注释的文字，将无法看清注释

### ISSUE THREAD

**Issue by yupeilin123** [robb0wen/synthwave-vscode#71]
正常的显示
![image](https://user-images.githubusercontent.com/28672197/57744743-0ee1e700-76fd-11e9-9830-e657aff1a88f.png)

双击后的显示
![image](https://user-images.githubusercontent.com/28672197/57744901-a0515900-76fd-11e9-8e7b-9a81c3782a2d.png)

**Comment by robb0wen** [comment]
Hmmm对比度不很好. OK! 
I'll fix it in the next version.
