### ISSUE TITLE
Use of red in token colours is misleading

### ISSUE THREAD

**Issue by ben-homepass** [robb0wen/synthwave-vscode#80]
Thank you for creating such a gorgeous theme.

I have just one small suggestion/request. Some identifiers (I think mostly type names?) in TypeScript are coloured red.

![Screen Shot 2019-06-25 at 10 56 48 am](https://user-images.githubusercontent.com/50093279/60061297-f4f1e600-9737-11e9-999b-898431dcd44d.png)

It would be much better imo to avoid red altogether as many developers associate this colour with problems in the code. Could we change the colour of these tokens to something else please?

**Comment by Thomas-James-Rose** [comment]
> It would be much better imo to avoid red altogether as many developers associate this colour with problems in the code.

I disagree - lots of themes use red text. If there is a problem with your code, VSCode will highlight it with a pretty distinct wavy underline.
