### ISSUE TITLE
markdown support

### ISSUE THREAD

**Issue by chadlavi** [robb0wen/synthwave-vscode#81]
This theme is great!

One thing it breaks for me, though, is markdown formatting. VS Code does a pretty good job of this in their standard themes.

Here's the default theme (Dark+):
<img width="574" alt="Screen Shot 2019-06-28 at 3 25 49 PM" src="https://user-images.githubusercontent.com/7226642/60366295-20373800-99b9-11e9-9da4-4cf530d14ee0.png">

And here's your theme: 
<img width="568" alt="Screen Shot 2019-06-28 at 3 26 12 PM" src="https://user-images.githubusercontent.com/7226642/60366305-25948280-99b9-11e9-8331-482f2a507899.png">

Things like bold, italics, code snippets, and lists are not styled in your theme.

**Comment by twhite96** [comment]
Yeah looking for this too. If you'd like any help @robb0wen I can see what I can do.

**Comment by robb0wen** [comment]
Updated in v0.1.8 :)
