### ISSUE TITLE
Feature Request: I need glowing brackets!!!

### ISSUE THREAD

**Issue by petercr** [robb0wen/synthwave-vscode#82]
**Great job** with your theme, I absolutely love it! 🥇 😍 
Any chance in the future you will make it so the brackets glow as well?
Especially the curly `{ }` and round `( )` brackets. Some of them do, but some of them don't

I feel like it kind of takes away from the theme a little bit, but that's just me.

Thanks 

Here's a screenshot where you can see some of the brackets are just a dull grey

![2019-06-30](https://user-images.githubusercontent.com/26460352/60402239-d5edbc80-9b5a-11e9-9b7c-8914e1eab926.png)

**Comment by robb0wen** [comment]
It's something that I could look into, though my main reason for not doing it is that I know many devs use bracket highlighter extensions and I don't want to open the theme up too much to interfering with those. That said, when I get chance, I'll see what can be done. 

In the meantime, if you install Bracket pair Coloriser extension, you'll get some sweet neon coloured brackets that fit well with the theme

**Comment by petercr** [comment]
Cool I'm a **huge fan** of Bracket Pair Colorizer 2 and yes I usually use it. I actually turned if off for the screenshot 😉  But still _I don't know_ if you can pass in `text-shadow`s into it's color scheme. 
I'll give it a try and see what I come up with 👍

**Comment by petercr** [comment]
Okay fine I'll just clone the repo and make them glow for myself 😢 
Probably for the best anyways then I'll learn more about **VS Code** 

Thanks again for making such a cool extension 👍
