### ISSUE TITLE
Change bracket glow & Change object path color

### ISSUE THREAD

**Issue by gfsd3v** [robb0wen/synthwave-vscode#86]
Hi.

I'm trying to customize the CSS but I wasn't able to find how to change the object path color and remove the bracket glow, can anyone give me some help on that ?

I highlighted the things I want to change for better understandment.
 
![alt text](https://i.imgur.com/SLLoq0Q.png)

Thanks in advance.

**Comment by willstocks-tech** [comment]
Do you use bracket pair colorizer by chance?

I recently whipped up a file that increases the glow - but essentially you have to do this yourself (see https://github.com/robb0wen/synthwave-vscode/issues/82#issuecomment-508689480) as, understandably, the theme can't cater for every single different bracket stylizer!

**Comment by kanta-mir** [comment]
Hi every one
![image](https://user-images.githubusercontent.com/2287000/132254369-f9a9f6cf-f595-4bfb-9112-559a0d4bbd8f.png)
I am getting this error when I try to enable glow. 
any idea ? thanks

**Comment by kanta-mir** [comment]
@willstocks  have you uploaded your solution to highlight the brackets anywhere, I would like to use it . Thanks

**Comment by willstocks** [comment]
@kanta-mir it's slightly different with the latest update as I'm no longer using BPC and am relying on native bracket coloring. I haven't had a chance to refactor yet as it appears to work slightly differently.
