### ISSUE TITLE
Not compatible with vs 1.20.0

### ISSUE THREAD

**Issue by alvico** [robb0wen/synthwave-vscode#9]
When trying to install it in my vstudio code I've got the error that it is not compatible with the latest version 1.20.0.

**Comment by jarcane** [comment]
Also not compatible with 1.31.1.

**Comment by mdvorscak** [comment]
I get the error: `Cannot read property 'id' of undefined` when trying to set the theme

**Comment by fernandezpablo85** [comment]
Also not compatible with `1.32.3`

**Comment by LiamRR** [comment]
Also not compatible with Version 1.23.1 (1.23.1) on macOS Mojave 10.14.4

Error:
`Unable to install 'RobbOwen.synthwave-vscode'; there is no available version compatible with VS Code '1.23.1'.`

**Comment by f4ww4z** [comment]
Also not working with version `1.33.1`.

**Comment by robb0wen** [comment]
I generated the theme with the VS code yeoman generator and it set the latest engine value in the package json to be 1.33.0 so it should work from that version and up. I'll see if I can update it to be lower.

**Comment by alvico** [comment]
I've updated manually to the latest version and it works, fine, somehow I was stuck in an older version and it was refusing to update itself.

**Comment by mdvorscak** [comment]
Uninstalling and reinstalling seems to have fixed the issue, thanks!

**Comment by SolalVall** [comment]
Like @robb0wen said, by default you can't install an extension when his version is greater than your vscode version.

A way to make it works for prior version maybe, is to reduce the version requirements in package.json
```
"engines": {
        "vscode": "^1.33.0"
},
```

To (for example):

```
"engines": {
        "vscode": "^1.20.0"
},
```

Tag this revision to v0.0.1 for example.

Then it will be possible to download a prior version of an extension by adding the specific tag in the URL:
https://ms-vscode.gallery.vsassets.io/_apis/public/gallery/publisher/{ owner }/extension/{ extension_name }/{ version }/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage

In my example it will look like this:
https://ms-vscode.gallery.vsassets.io/_apis/public/gallery/publisher/RobbOwen/extension/synthwave-vscode/0.0.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage

Once downloaded the user can manually add the extension to vsocde:
https://vscode-docs.readthedocs.io/en/stable/extensions/install-extension/

**Comment by robb0wen** [comment]
Thanks! I've given this a lot of though and, whilst I was considering reducing the version number to allow it to be installed on older editions, I've decided it's best to leave it as-is. 1.33.0 is the minimum install version.

Until VS Code adds support for custom CSS natively, adding the glow to the theme is experimental (read: a bit of a hack). Locking it at 1.33.0 I at least know it's possible to get it working with the versions of VS Code, and the Custom CSS and JS extension at the time of the original launch. The installation is already messy and I don't want to muddy it further, or risk editor instability, by introducing older versions into the mix.

**Comment by zanzee** [comment]
Isnt it possible to add 1.31.0 without the glow ?

I really loved the theme, but I work on a HUGE bank in brazil and we can't update our apps without our infrastructure approvals. 

:(
