### ISSUE TITLE
Glow not working 

### ISSUE THREAD

**Issue by varogonz95** [robb0wen/synthwave-vscode#97]
Hi, first I must say this is an amazing work, I really love this theme
But as the title says, glow is not working.
In my installation, the theme doesn't look like the demo picture

#### Details
Version: 1.37.1 (user setup)
Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Date: 2019-08-15T16:17:55.855Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 6.3.9600

**Comment by stevealexandre** [comment]
Hi dude,

Can you give us your configuration json ?
We can't debug without more information.

**Comment by robb0wen** [comment]
There's a new way to enable the glow. Please update to v0.1.0 of the theme and follow the instructions in the readme.

I'll close this issue for now as it is related to a previous version.
